/*
 * marketplace_createTransfer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.marketplace;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.TransferFromDetail;
import com.alipay.global.api.model.ams.TransferToDetail;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayCreateTransferResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCreateTransferResponse extends AlipayResponse {

  /**
   * The unique ID assigned by Antom to identify a transfer. This parameter is returned when the
   * value of result.resultStatus is U. More information: Maximum length: 64 characters
   */
  private String transferId;

  /**
   * The unique ID assigned by the marketplace to identify a transfer request. This parameter is
   * returned when the value of result.resultStatus is U. More information: Maximum length: 64
   * characters
   */
  private String transferRequestId;

  private TransferFromDetail transferFromDetail;

  private TransferToDetail transferToDetail;
}
