/*
 * payments_downloadDisputeEvidence
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.dispute;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.DisputeEvidenceFormatType;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayDownloadDisputeEvidenceResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayDownloadDisputeEvidenceResponse extends AlipayResponse {

  /**
   * The dispute evidence that is encoded in the Based64 format. Decode the Base64 document to get
   * the Word or PDF file. Note: This prameter is returned when the value of resultCode is SUCCESS.
   * More information: Maximum length: 1000000 characters
   */
  private String disputeEvidence;

  private DisputeEvidenceFormatType disputeEvidenceFormat;
}
