/*
 * v1_billing_price_create
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Amount;
import com.alipay.global.api.model.ams.RecurringSettings;
import com.alipay.global.api.model.ams.Tier;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayPriceCreateResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayPriceCreateResponse extends AlipayResponse {

  /**
   * System-generated price ID. Format: price_ prefix + alphanumeric suffix Returned only when
   * result.resultCode is SUCCESS.
   */
  private String priceId;

  /**
   * Echo of the idempotent request key from the request. O - May be null in the response when the
   * value is not set Returned only when result.resultCode is SUCCESS.
   */
  private String priceRequestId;

  /** Associated product ID Returned only when result.resultCode is SUCCESS. */
  private String productId;

  /**
   * Price name. O - May be null in the response when the value is not set Returned only when
   * result.resultCode is SUCCESS.
   */
  private String name;

  /**
   * Pricing model type. Always returned - either provided by merchant or derived per Default
   * Derivation rules. Enum: PER_UNIT(per-unit pricing aligned with Stripe
   * billing_scheme&#x3D;per_unit), TIERED(tiered pricing aligned with Stripe
   * billing_scheme&#x3D;tiered). Forward compatibility: If a new value is added in the future,
   * clients that do not recognize it should treat it as an unknown value and not break Returned
   * only when result.resultCode is SUCCESS.
   */
  private String pricingModel;

  /**
   * Usage type. O - May be null in the response when the value is not set. Enum: LICENSED(fixed
   * license/per-seat - describes quantity tracking method), METERED(metered usage - describes
   * quantity tracking method). Forward compatibility: If a new value is added in the future,
   * clients that do not recognize it should treat it as an unknown value and not break Returned
   * only when result.resultCode is SUCCESS.
   */
  private String usageType;

  /**
   * Price-level unit label. O - May be null in the response when the value is not set Returned only
   * when result.resultCode is SUCCESS.
   */
  private String unitLabel;

  /**
   * External meter reference. O - May be null in the response when the value is not set Returned
   * only when result.resultCode is SUCCESS.
   */
  private String meterId;

  private Amount unitAmount;

  private RecurringSettings recurring;

  /**
   * Price active status. true&#x3D;price is active and can be used for new subscriptions,
   * false&#x3D;price is deactivated and cannot be used for new subscriptions. Default on creation:
   * true. Cannot be null Returned only when result.resultCode is SUCCESS.
   */
  private Boolean active;

  /**
   * Included quantity for package pricing. O - May be null in the response when the value is not
   * set Returned only when result.resultCode is SUCCESS.
   */
  private Long includedQuantity;

  /**
   * Tiered pricing mode. O - May be null in the response when the value is not set. Enum:
   * GRADUATED(graduated pricing - each tier priced independently, customer may cross tiers),
   * VOLUME(volume pricing - single tier rate applies to entire quantity). Forward compatibility: If
   * a new value is added in the future, clients that do not recognize it should treat it as an
   * unknown value and not break Returned only when result.resultCode is SUCCESS.
   */
  private String tiersMode;

  /**
   * Tier definitions. O - May be null in the response when the value is not set Returned only when
   * result.resultCode is SUCCESS.
   */
  private List<Tier> tiers;

  /**
   * Metadata encoded as a JSON object string. Returned only when &#x60;result.resultCode&#x60; is
   * &#x60;SUCCESS&#x60; and metadata was set. The SDK must expose the stored string unchanged.
   */
  private String metadata;

  /** ISO 8601 creation timestamp Returned only when result.resultCode is SUCCESS. */
  private String createdAt;

  /**
   * ISO 8601 last update timestamp. O - May be null in the response when the value is not set
   * Returned only when result.resultCode is SUCCESS.
   */
  private String updatedAt;

  /**
   * Whether this price is the default price for the product. When true, this price is the primary
   * price shown for the product Returned only when result.resultCode is SUCCESS.
   */
  private Boolean defaultPrice;
}
