/*
 * v1_billing_promotionCode_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.PromotionCodeInfo;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayPromotionCodeInquireListResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayPromotionCodeInquireListResponse extends AlipayResponse {

  /**
   * List of promotion code summary items. Maximum size: 100 elements per page (governed by request
   * &#x60;limit&#x60; max value 100). Empty array if no results. Returned when resultCode is
   * &#x60;SUCCESS&#x60;.
   */
  private List<PromotionCodeInfo> promotionCodes;

  /**
   * Whether more results exist beyond the current page. &#x60;false&#x60; &#x3D; last page.
   * Returned when resultCode is &#x60;SUCCESS&#x60;.
   */
  private Boolean hasMore;

  /**
   * Entity ID of the last element. Pass as &#x60;startingAfter&#x60; in the next request. Returned
   * when &#x60;hasMore&#x60; is &#x60;true&#x60;. Absent when &#x60;hasMore&#x60; is
   * &#x60;false&#x60;. Returned only when result.resultCode is SUCCESS.
   */
  private String nextCursor;

  /**
   * Total count of matching promotion codes. Only returned when request has
   * &#x60;includeTotal&#x3D;true&#x60;. Returned only when result.resultCode is SUCCESS.
   */
  private Integer total;

  /**
   * Entity ID of the first element. Pass as &#x60;endingBefore&#x60; to navigate backward. Only
   * returned when request used &#x60;endingBefore&#x60;. Returned only when result.resultCode is
   * SUCCESS.
   */
  private String previousCursor;
}
