/*
 * v1_billing_customer_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Customer;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayCustomerInquireListResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCustomerInquireListResponse extends AlipayResponse {

  /**
   * List of customer summary items. Maximum size: 100 elements (bounded by &#x60;limit&#x60;).
   * Empty array if no results. Returned when resultCode is &#x60;SUCCESS&#x60;. Each item is a slim
   * 9-field projection (see below).
   */
  private List<Customer> customers;

  /**
   * Total count of matching customers. Only returned when request has
   * &#x60;includeTotal&#x3D;true&#x60;. Returned only when result.resultCode is SUCCESS.
   */
  private Integer total;

  /**
   * Whether more results exist beyond the current page. &#x60;false&#x60; &#x3D; last page.
   * Returned when resultCode is &#x60;SUCCESS&#x60;.
   */
  private Boolean hasMore;

  /**
   * The &#x60;customerId&#x60; of the last element in the current page. Pass as
   * &#x60;startingAfter&#x60; in the next request. Returned when &#x60;hasMore&#x60; is
   * &#x60;true&#x60;. Absent when &#x60;hasMore&#x60; is &#x60;false&#x60;. Returned only when
   * result.resultCode is SUCCESS.
   */
  private String nextCursor;

  /**
   * Returned only in BACKWARD (&#x60;endingBefore&#x60;) navigation. The &#x60;customerId&#x60; of
   * the first item in the current page. Pass as &#x60;endingBefore&#x60; in the previous-page
   * request. Absent in forward navigation. Returned only when result.resultCode is SUCCESS.
   */
  private String previousCursor;
}
