/*
 * v1_billing_coupon_update
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayCouponUpdateResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCouponUpdateResponse extends AlipayResponse {

  /** Updated coupon&#39;s ID. Returned when resultCode is &#x60;SUCCESS&#x60;. */
  private String couponId;

  /** Coupon status after update. Returned when resultCode is &#x60;SUCCESS&#x60;. */
  private String status;
}
