/*
 * v1_billing_subscription_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.BillingSubscriptionInquireDetailsCancellationDetails;
import com.alipay.global.api.model.ams.BillingSubscriptionInquireDetailsPauseCollection;
import com.alipay.global.api.model.ams.BillingSubscriptionInquireDetailsTrialSettings;
import com.alipay.global.api.model.ams.Discount;
import com.alipay.global.api.model.ams.SubscriptionItem;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import java.util.Map;
import lombok.*;

/** AlipayBillingSubscriptionInquireDetailsResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayBillingSubscriptionInquireDetailsResponse extends AlipayResponse {

  /** The subscription ID. Maximum length: 64 characters. */
  private String subscriptionId;

  /**
   * The subscription request id. Maximum length: 64 characters. Note: See documentation for
   * details.
   */
  private String subscriptionRequestId;

  /** The created at. */
  private String createdAt;

  /** The current status. Maximum length: 20 characters. */
  private String status;

  /** The current period start. */
  private String currentPeriodStart;

  /** The current period end. */
  private String currentPeriodEnd;

  /** The billing cycle anchor. Note: See documentation for details. */
  private String billingCycleAnchor;

  /** The cancel at period end. */
  private Boolean cancelAtPeriodEnd;

  /** The canceled at. Note: See documentation for details. */
  private String canceledAt;

  /** The trial start. Note: See documentation for details. */
  private String trialStart;

  /** The trial end. Note: See documentation for details. */
  private String trialEnd;

  private BillingSubscriptionInquireDetailsTrialSettings trialSettings;

  private BillingSubscriptionInquireDetailsPauseCollection pauseCollection;

  /** The cancel at. Note: See documentation for details. */
  private String cancelAt;

  /** The collection method. Maximum length: 22 characters. */
  private String collectionMethod;

  /** The days until due. Note: See documentation for details. */
  private Integer daysUntilDue;

  private BillingSubscriptionInquireDetailsCancellationDetails cancellationDetails;

  /** The termination reason. Maximum length: 64 characters. Note: See documentation for details. */
  private String terminationReason;

  /** The description. Maximum length: 500 characters. */
  private String description;

  /**
   * The default payment method token. Maximum length: 64 characters. Note: See documentation for
   * details.
   */
  private String defaultPaymentMethod;

  /** The subscription items. Maximum length: 20 characters. */
  private List<SubscriptionItem> subscriptionItems;

  /** The discounts applied. Note: See documentation for details. */
  private List<Discount> discounts;

  /** Custom metadata for special use cases. Note: See documentation for details. */
  private Map<String, String> metadata;
}
