/*
 * v1_billing_invoice_confirmPayment
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayInvoiceConfirmPaymentResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInvoiceConfirmPaymentResponse extends AlipayResponse {

  /** The invoice ID. Maximum length: 64 characters. */
  private String invoiceId;

  /** The current status. Maximum length: 16 characters. */
  private String status;

  /** The receipt ID. Maximum length: 64 characters. */
  private String receiptId;

  /** The invoice note. Maximum length: 512 characters. */
  private String invoiceNote;

  /** The paid at. Maximum length: 24 characters. */
  private String paidAt;

  /**
   * The email sending status. Maximum length: 16 characters. Note: See documentation for details.
   */
  private String sendStatus;
}
