/*
 * v1_billing_promotionCode_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.PromotionCodeInquireDetailsMinAmount;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayPromotionCodeInquireDetailsResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayPromotionCodeInquireDetailsResponse extends AlipayResponse {

  /** System-generated promotion code ID. Returned when resultCode is &#x60;SUCCESS&#x60;. */
  private String promotionCodeId;

  /**
   * Merchant-supplied idempotency key used at creation. Returned when resultCode is
   * &#x60;SUCCESS&#x60;.
   */
  private String promotionCodeRequestId;

  /** The promotion code string. Returned when resultCode is &#x60;SUCCESS&#x60;. */
  private String code;

  /** Parent coupon&#39;s ID. Returned when resultCode is &#x60;SUCCESS&#x60;. */
  private String couponId;

  /**
   * Promotion code status: &#x60;ACTIVE&#x60; / &#x60;INACTIVE&#x60; only - the DB persists these
   * two values and no &#x60;EXPIRED&#x60; status is derived at read time. A promotion code past its
   * &#x60;expiryTime&#x60; is no longer redeemable; compare &#x60;expiryTime&#x60; to the current
   * time to detect expiry. Future status values may be added; merchants must handle unrecognized
   * values gracefully (log and skip). Returned only when result.resultCode is SUCCESS.
   */
  private String status;

  /**
   * Maximum redemption count. Value range: 0-999999. Returned when resultCode is
   * &#x60;SUCCESS&#x60;.
   */
  private Integer maxRedemptions;

  /**
   * Number of times the promotion code has been redeemed. Value range: 0-999999. Returned when
   * resultCode is &#x60;SUCCESS&#x60;.
   */
  private Integer redeemedCount;

  /**
   * Expiry time (UTC, ISO 8601). Returned when resultCode is &#x60;SUCCESS&#x60; and the field was
   * set.
   */
  private String expiryTime;

  private PromotionCodeInquireDetailsMinAmount minAmount;

  /** Whether code is one-time per customer. Returned when resultCode is &#x60;SUCCESS&#x60;. */
  private Boolean oneTimeOnly;

  /**
   * Restricted customer&#39;s ID. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was
   * set.
   */
  private String customerId;

  /**
   * Merchant-defined key-value pairs. Returned when resultCode is &#x60;SUCCESS&#x60; and the field
   * was set. The value must be a valid JSON object string.
   */
  private String metadata;

  /** Creation time (UTC, ISO 8601). Returned when resultCode is &#x60;SUCCESS&#x60;. */
  private String createTime;
}
