/*
 * v1_billing_subscription_resume
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayBillingSubscriptionResumeResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayBillingSubscriptionResumeResponse extends AlipayResponse {

  /**
   * The resumed subscription ID. Returned only when result.resultCode is SUCCESS or
   * PAYMENT_IN_PROCESSING. Maximum length: 64 characters.
   */
  private String subscriptionId;

  /**
   * The subscription status after the resume attempt. ACTIVE indicates that payment succeeded;
   * PAUSED indicates that payment is still processing or failed. Returned only when the operation
   * produced a subscription result. Maximum length: 20 characters.
   */
  private String status;

  /**
   * The effective billing cycle anchor after the subscription is resumed, represented as an ISO
   * 8601 date-time string with a timezone offset. Returned when the billing cycle is reset.
   */
  private String billingCycleAnchor;
}
