/*
 * v1_billing_invoice_createViewLink
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayInvoiceCreateViewLinkResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInvoiceCreateViewLinkResponse extends AlipayResponse {

  /**
   * Encrypted token embedding &#x60;invoiceId&#x60;, &#x60;merchantId&#x60;, and
   * &#x60;expiryTimestamp&#x60; in the pipe-delimited format
   * &#x60;invoiceId|merchantId|expiryTimestamp&#x60; (e.g.,
   * &#x60;inv_20260413_000123|MID_001|1713590400000&#x60;). Encrypted via AES-CBC through iBCM. See
   * Token Structure section for full details. Returned only when result.resultCode is SUCCESS.
   */
  private String token;

  /**
   * Full shareable URL for the invoice view page. Format:
   * &#x60;{baseUrl}?token&#x3D;{encodedToken}&#x60;. Returned when &#x60;resultStatus&#x60; is
   * &#x60;S&#x60; and &#x60;resultCode&#x60; is &#x60;SUCCESS&#x60;, and DRM &#x60;baseUrl&#x60; is
   * configured. When DRM &#x60;baseUrl&#x60; is not configured, this field is absent (not
   * returned); the &#x60;token&#x60; is still returned and merchants can construct the URL
   * client-side. Returned only when result.resultCode is SUCCESS.
   */
  private String viewUrl;

  /**
   * ISO 8601 absolute timestamp indicating when the token and view link expire. Calculated as:
   * &#x60;requestProcessingTime + (linkExpiryDays x 86400 seconds)&#x60;, then rounded UP to the
   * start of the following UTC day. This means the effective link validity is always slightly
   * longer than requested (up to ~24 hours extra). When &#x60;linkExpiryDays&#x60; is not provided,
   * the default of 7 days is used. Example: request at &#x60;2026-04-13T10:00:00Z&#x60; + 7 days
   * &#x3D; calculated expiry &#x60;2026-04-20T10:00:00Z&#x60;, rounded up to
   * &#x60;2026-04-21T00:00:00Z&#x60;. The link is valid until midnight UTC of the day after the
   * calculated expiry. Format: &#x60;yyyy-MM-dd&#39;T&#39;HH:mm:ss&#39;Z&#39;&#x60; (e.g.,
   * &#x60;2026-04-21T00:00:00Z&#x60;). Returned when &#x60;resultStatus&#x60; is &#x60;S&#x60; and
   * &#x60;resultCode&#x60; is &#x60;SUCCESS&#x60;. Cannot be null when present. Returned only when
   * result.resultCode is SUCCESS.
   */
  private String expiresAt;
}
