/*
 * v1_billing_coupon_update
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import java.util.Map;
import lombok.*;

/** AlipayCouponUpdateResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCouponUpdateResponse extends AlipayResponse {

  /** The coupon ID. Maximum length: 64 characters. Note: See documentation for details. */
  private String couponId;

  /** The coupon name. Maximum length: 128 characters. Note: See documentation for details. */
  private String couponName;

  /** The current status. Maximum length: 16 characters. Note: See documentation for details. */
  private String status;

  /** The max redemptions. Note: See documentation for details. */
  private Integer maxRedemptions;

  /** The redeemed count. Note: See documentation for details. */
  private Integer redeemedCount;

  /** The redeem by. Note: See documentation for details. */
  private String redeemBy;

  /**
   * Custom metadata for special use cases. Maximum length: 65535 characters. Note: See
   * documentation for details.
   */
  private Map<String, String> metadata;

  /** The update time. Note: See documentation for details. */
  private String updateTime;
}
