/*
 * v1_billing_invoice_export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayInvoiceExportResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInvoiceExportResponse extends AlipayResponse {

  /** The current status. Maximum length: 16 characters. */
  private String status;

  /** The download url. Maximum length: 2048 characters. Note: See documentation for details. */
  private String downloadUrl;

  /** The expiration time. Maximum length: 24 characters. */
  private String expiresAt;
}
