/*
 * v1_billing_customer_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayCustomerInquireDetailsResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCustomerInquireDetailsResponse extends AlipayResponse {

  /** System-generated customer ID. Returned when resultCode is &#x60;SUCCESS&#x60;. */
  private String customerId;

  /**
   * Merchant-supplied idempotency key used at creation. Returned when resultCode is
   * &#x60;SUCCESS&#x60;.
   */
  private String customerRequestId;

  /**
   * Bound Alipay user ID for channel routing and risk control. Returned when resultCode is
   * &#x60;SUCCESS&#x60; and the field was set; omitted (not returned as null) if not set.
   */
  private String alipayUserId;

  /**
   * Customer email address. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set.
   */
  private String email;

  /** Customer first name. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set. */
  private String firstName;

  /** Customer last name. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set. */
  private String lastName;

  /**
   * Billing address country (ISO 3166-1 alpha-2). Returned when resultCode is &#x60;SUCCESS&#x60;
   * and the field was set.
   */
  private String country;

  /**
   * Billing address state. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set.
   */
  private String state;

  /**
   * Billing address city. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set.
   */
  private String city;

  /**
   * Billing address street line 1. Returned when resultCode is &#x60;SUCCESS&#x60; and the field
   * was set.
   */
  private String address;

  /**
   * Billing address street line 2. Returned when resultCode is &#x60;SUCCESS&#x60; and the field
   * was set.
   */
  private String addressDetail;

  /**
   * Billing address postal code. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was
   * set.
   */
  private String zipcode;

  /** Shipping phone. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set. */
  private String shippingPhone;

  /**
   * Shipping country (ISO 3166-1 alpha-2). Returned when resultCode is &#x60;SUCCESS&#x60; and the
   * field was set.
   */
  private String shippingCountry;

  /** Shipping state. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set. */
  private String shippingState;

  /** Shipping city. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set. */
  private String shippingCity;

  /**
   * Shipping street line 1. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set.
   */
  private String shippingAddress;

  /**
   * Shipping street line 2. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set.
   */
  private String shippingAddressDetail;

  /**
   * Free-text description. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set.
   */
  private String description;

  /**
   * Default currency (ISO 4217). Returned when resultCode is &#x60;SUCCESS&#x60; and the field was
   * set.
   */
  private String currency;

  /**
   * Preferred locale(s). Maximum size: 5 elements. Returned when resultCode is &#x60;SUCCESS&#x60;
   * and the field was set.
   */
  private List<String> preferredLocales;

  /**
   * Default payment method token. Sourced from &#x60;defaultCustomerPaymentMethodId&#x60;. Returned
   * when resultCode is &#x60;SUCCESS&#x60; and the field was set.
   */
  private String defaultPaymentMethod;

  /**
   * Customer status: &#x60;ACTIVE&#x60; / &#x60;DELETED&#x60;. Returned when resultCode is
   * &#x60;SUCCESS&#x60;.
   */
  private String status;

  /**
   * Merchant&#39;s internal customer ID reference. Returned when resultCode is &#x60;SUCCESS&#x60;
   * and the field was set.
   */
  private String referenceCustomerId;

  /**
   * Merchant-defined metadata encoded as a JSON object string. Maximum length: 500 characters.
   * Returned only when result.resultCode is SUCCESS and the field was set.
   */
  private String metadata;

  /**
   * Customer phone number (digits only). Returned when resultCode is &#x60;SUCCESS&#x60; and the
   * field was set.
   */
  private String phoneNo;

  /**
   * ISO 3166-1 alpha-2 country code paired with &#x60;phoneNo&#x60;. Returned when resultCode is
   * &#x60;SUCCESS&#x60; and the field was set.
   */
  private String countryCode;

  /**
   * Invoice recipient email (independent of account &#x60;email&#x60;). Returned when resultCode is
   * &#x60;SUCCESS&#x60; and the field was set.
   */
  private String billingEmail;

  /**
   * Shipping recipient first name. Returned when resultCode is &#x60;SUCCESS&#x60; and the field
   * was set.
   */
  private String shippingFirstName;

  /**
   * Shipping recipient last name. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was
   * set.
   */
  private String shippingLastName;

  /**
   * Shipping address numeric calling code. Returned when resultCode is &#x60;SUCCESS&#x60; and the
   * field was set.
   */
  private String shippingCountryCode;

  /**
   * Shipping postal code. Wire name: &#x60;shippingZipcode&#x60;. Returned when resultCode is
   * &#x60;SUCCESS&#x60; and the field was set.
   */
  private String shippingZipcode;

  /**
   * Customer creation timestamp. Note: there is NO &#x60;updateTime&#x60; / &#x60;gmtModified&#x60;
   * field on &#x60;CustomerQueryDetailsResult&#x60;. Returned only when result.resultCode is
   * SUCCESS.
   */
  private String gmtCreate;
}
