/*
 * v1_billing_customer_createPortalLink
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayCustomerCreatePortalLinkResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCustomerCreatePortalLinkResponse extends AlipayResponse {

  /**
   * Opaque URL-safe bearer token. Treat it as a credential: do not log, parse, or store its
   * internal structure because the format may change without notice. Maximum length: 4096
   * characters. Returned only when result.resultCode is SUCCESS.
   */
  private String token;

  /**
   * Fully-qualified portal URL. Null when the portal base URL is not configured for the merchant;
   * in that case, build the URL from &#x60;token&#x60;. Maximum length: 2048 characters. Returned
   * only when result.resultCode is SUCCESS.
   */
  private String portalUrl;

  /**
   * Expiration time of the portal link, returned as a string. Maximum length: 32 characters.
   * Returned only when result.resultCode is SUCCESS.
   */
  private String expiresAt;

  /**
   * Email send status. Valid values are &#x60;SENT&#x60; and &#x60;FAILED&#x60;. Populated only
   * when request &#x60;autoSend&#x3D;true&#x60;; a send failure never blocks link creation. Null
   * when &#x60;autoSend&#x3D;false&#x60;. Maximum length: 16 characters. Returned only when
   * result.resultCode is SUCCESS.
   */
  private String sendStatus;
}
