/*
 * v1_billing_coupon_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayCouponInquireListResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCouponInquireListResponse extends AlipayResponse {

  private Array coupons;

  /** The has more. Note: See documentation for details. */
  private Boolean hasMore;

  /** The next cursor. Maximum length: 64 characters. Note: See documentation for details. */
  private String nextCursor;

  /** The prev cursor. Maximum length: 64 characters. Note: See documentation for details. */
  private String prevCursor;

  /** The total. Note: See documentation for details. */
  private Integer total;
}
