/*
 * v1_billing_product_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Price;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import java.util.Map;
import lombok.*;

/** AlipayProductInquireDetailsResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayProductInquireDetailsResponse extends AlipayResponse {

  /** The product ID. Maximum length: 32 characters. */
  private String productId;

  /** The name. Maximum length: 100 characters. */
  private String name;

  /** The type. Maximum length: 16 characters. */
  private String type;

  /** The description. Maximum length: 1024 characters. */
  private String description;

  /** The images. */
  private List<String> images;

  /** The unit label. Maximum length: 64 characters. */
  private String unitLabel;

  /** Custom metadata for special use cases. */
  private Map<String, String> metadata;

  /** The active. */
  private Boolean active;

  /** The created at. Maximum length: 29 characters. */
  private String createdAt;

  /** The deactivated at. Maximum length: 29 characters. Note: See documentation for details. */
  private String deactivatedAt;

  /** The updated at. Maximum length: 29 characters. Note: See documentation for details. */
  private String updatedAt;

  /** The prices. Note: See documentation for details. */
  private List<Price> prices;

  /** The has more prices. Note: See documentation for details. */
  private Boolean hasMorePrices;
}
