/*
 * v1_billing_product_create
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayProductCreateResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayProductCreateResponse extends AlipayResponse {

  /**
   * System-generated product ID. Format: prod_ prefix + alphanumeric suffix (e.g., prod_2xK8mN3pQ7)
   * Returned only when result.resultCode is SUCCESS.
   */
  private String productId;

  /**
   * Echo of the idempotent request key from the request. O - May be null in the response when the
   * value is not set Returned only when result.resultCode is SUCCESS.
   */
  private String productRequestId;

  /** Product name. Echo of request value Returned only when result.resultCode is SUCCESS. */
  private String name;

  /**
   * Product type. Enum: SERVICE(intangible digital service or SaaS offering - checkout skips
   * shipping address collection), GOOD(tangible physical product requiring delivery - checkout
   * collects shipping address). Echo of request value (or default SERVICE if not provided). Forward
   * compatibility: If a new value is added in the future, clients that do not recognize it should
   * treat it as an unknown value and not break Returned only when result.resultCode is SUCCESS.
   */
  private String type;

  /**
   * Product description. O - May be null in the response when the value is not set Returned only
   * when result.resultCode is SUCCESS.
   */
  private String description;

  /**
   * Product image URLs. O - Returned when non-null and non-empty; absent if null or empty Returned
   * only when result.resultCode is SUCCESS.
   */
  private List<String> images;

  /**
   * Product-level unit label. O - May be null in the response when the value is not set Returned
   * only when result.resultCode is SUCCESS.
   */
  private String unitLabel;

  /**
   * Metadata encoded as a JSON object string. Returned only when &#x60;result.resultCode&#x60; is
   * &#x60;SUCCESS&#x60; and metadata was set. The SDK must expose the stored string unchanged.
   */
  private String metadata;

  /**
   * Product active status. true&#x3D;product is active and can be used for new subscriptions,
   * false&#x3D;product is deactivated and cannot be used for new subscriptions. Default: true.
   * Cannot be null. Deactivated products can be reactivated via Update active&#x3D;true Returned
   * only when result.resultCode is SUCCESS.
   */
  private Boolean active;

  /**
   * ISO 8601 creation timestamp. Cannot be null Returned only when result.resultCode is SUCCESS.
   */
  private String createdAt;

  /**
   * ISO 8601 deactivation timestamp. O - Returned when product has been deactivated
   * (active&#x3D;false); absent when product is active Returned only when result.resultCode is
   * SUCCESS.
   */
  private String deactivatedAt;

  /**
   * ISO 8601 last update timestamp. O - Returned when non-null; absent from response if never
   * updated after creation Returned only when result.resultCode is SUCCESS.
   */
  private String updatedAt;
}
