/*
 * v1_billing_coupon_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Amount;
import com.alipay.global.api.model.ams.CouponInquireDetailsAppliesTo;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayCouponInquireDetailsResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCouponInquireDetailsResponse extends AlipayResponse {

  /** System-generated coupon ID. Returned when resultCode is &#x60;SUCCESS&#x60;. */
  private String couponId;

  /**
   * Merchant-supplied idempotency key used at creation. Returned when resultCode is
   * &#x60;SUCCESS&#x60;.
   */
  private String couponRequestId;

  /** Coupon display name. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set. */
  private String couponName;

  /**
   * Discount type: &#x60;PERCENT&#x60; or &#x60;AMOUNT&#x60;. Returned when resultCode is
   * &#x60;SUCCESS&#x60;.
   */
  private String discountType;

  /**
   * Percentage discount value (up to 2 decimal places). Returned when &#x60;discountType&#x60;
   * &#x3D; &#x60;PERCENT&#x60;. Returned only when result.resultCode is SUCCESS.
   */
  private String percentOff;

  private Amount amountOff;

  /**
   * Duration type: &#x60;ONCE&#x60; / &#x60;REPEATING&#x60; / &#x60;FOREVER&#x60;. Returned when
   * resultCode is &#x60;SUCCESS&#x60;.
   */
  private String durationType;

  /**
   * Duration value. Returned when &#x60;durationType&#x60; &#x3D; &#x60;REPEATING&#x60;. Returned
   * only when result.resultCode is SUCCESS.
   */
  private Integer durationValue;

  /**
   * Duration unit. Returned when &#x60;durationType&#x60; &#x3D; &#x60;REPEATING&#x60;. Returned
   * only when result.resultCode is SUCCESS.
   */
  private String durationUnit;

  /**
   * Redemption expiry time. Returned when resultCode is &#x60;SUCCESS&#x60; and the field was set.
   */
  private String redeemBy;

  private CouponInquireDetailsAppliesTo appliesTo;

  /**
   * Coupon status: &#x60;ACTIVE&#x60; / &#x60;INACTIVE&#x60;. Returned when resultCode is
   * &#x60;SUCCESS&#x60;. EXPIRED note (D-3): the system persists only
   * &#x60;ACTIVE&#x60;/&#x60;INACTIVE&#x60;; EXPIRED has no read-time derivation today. When
   * &#x60;status&#x60; is &#x60;ACTIVE&#x60;, compare &#x60;redeemBy&#x60; with the current time to
   * detect an expired coupon.
   */
  private String status;

  /**
   * Merchant-defined key-value pairs. Returned when resultCode is &#x60;SUCCESS&#x60; and the field
   * was set. The value must be a valid JSON object string.
   */
  private String metadata;

  /** Creation time (UTC, ISO 8601). Returned when resultCode is &#x60;SUCCESS&#x60;. */
  private String gmtCreate;

  /** Maximum redemption count. Returned when resultCode is &#x60;SUCCESS&#x60;. */
  private Integer maxRedemptions;

  /**
   * Number of times the coupon has been redeemed. Returned when resultCode is &#x60;SUCCESS&#x60;.
   */
  private Integer redeemedCount;
}
