/*
 * v1_tax_calculate
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Amount;
import com.alipay.global.api.model.ams.TaxBreakdown;
import com.alipay.global.api.model.ams.TaxCalculatedCustomerDetails;
import com.alipay.global.api.model.ams.TaxCalculatedLineItem;
import com.alipay.global.api.model.ams.TaxCalculatedShippingCost;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayTaxCalculateResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayTaxCalculateResponse extends AlipayResponse {

  /**
   * The unique ID assigned by Antom to identify a tax calculation. Maximum length: 64 characters.
   * Note: See documentation for details.
   */
  private String taxCalculationId;

  private Amount totalAmount;

  private Amount exclusiveTaxAmount;

  private Amount inclusiveTaxAmount;

  /** The line item list. Note: See documentation for details. */
  private List<TaxCalculatedLineItem> lineItems;

  /** The tax breakdown. Note: See documentation for details. */
  private List<TaxBreakdown> taxBreakdown;

  /** The expiration time. Maximum length: 32 characters. Note: See documentation for details. */
  private String expireAt;

  /** The tax date. Maximum length: 32 characters. */
  private String taxDate;

  private TaxCalculatedShippingCost shippingCost;

  private TaxCalculatedCustomerDetails customerDetails;
}
