/*
 * v1_billing_invoice_void
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayInvoiceVoidResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInvoiceVoidResponse extends AlipayResponse {

  /** The void request id. Maximum length: 64 characters. */
  private String voidRequestId;

  /** The invoice ID. Maximum length: 64 characters. */
  private String invoiceId;

  /** The current status. Maximum length: 16 characters. */
  private String status;

  /** The voided at. Maximum length: 24 characters. */
  private String voidedAt;

  /** The invoice note. Maximum length: 512 characters. */
  private String invoiceNote;
}
