/*
 * v1_billing_product_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Product;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayProductInquireListResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayProductInquireListResponse extends AlipayResponse {

  /**
   * Product list. Always present; empty array &#x60;[]&#x60; when no results. When products array
   * contains items, each Product object&#39;s M fields (productId, name, type, active, createdAt)
   * are mandatory Returned only when result.resultCode is SUCCESS.
   */
  private List<Product> products;

  /**
   * Whether more results exist beyond the current page. &#x60;true&#x60; if more results exist,
   * &#x60;false&#x60; otherwise. Detection logic: &#x60;hasMore &#x3D; (fetchedRows &#x3D;&#x3D;
   * limit + 1)&#x60; - the server fetches limit+1 rows; if the extra row exists, hasMore&#x3D;true
   * and only &#x60;limit&#x60; rows are returned. Aligned with Stripe cursor-based pagination
   * pattern Returned only when result.resultCode is SUCCESS.
   */
  private Boolean hasMore;

  /**
   * Total product count matching the query. O - Returned by default (includeTotal defaults to
   * true). Set includeTotal&#x3D;false to omit and avoid COUNT query latency. When present, enables
   * UI page navigation; when absent, use hasMore for \&quot;Load More\&quot; / infinite scroll
   * patterns Returned only when result.resultCode is SUCCESS.
   */
  private Integer total;
}
