/*
 * v1_meter_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Meter;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayMeterInquireListResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayMeterInquireListResponse extends AlipayResponse {

  /** The current page number. Returned only when result.resultCode is SUCCESS. */
  private Integer pageNum;

  /** The number of records on the current page. Returned only when result.resultCode is SUCCESS. */
  private Integer pageSize;

  /**
   * The total number of matching meters at query time. Returned only when result.resultCode is
   * SUCCESS.
   */
  private Integer totalCount;

  /** The matching meters. Returned only when result.resultCode is SUCCESS. */
  private List<Meter> meters;
}
