/*
 * v1_billing_customer_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import java.util.Map;
import lombok.*;

/** AlipayCustomerInquireDetailsResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCustomerInquireDetailsResponse extends AlipayResponse {

  /**
   * The unique ID assigned by Antom to identify a customer. Maximum length: 64 characters. Note:
   * See documentation for details.
   */
  private String customerId;

  /**
   * The unique ID assigned by a merchant to identify a request. Maximum length: 64 characters.
   * Note: See documentation for details.
   */
  private String customerRequestId;

  /** The Alipay user ID. Maximum length: 64 characters. Note: See documentation for details. */
  private String alipayUserId;

  /** The email address. Maximum length: 256 characters. Note: See documentation for details. */
  private String email;

  /** The first name. Maximum length: 256 characters. Note: See documentation for details. */
  private String firstName;

  /** The last name. Maximum length: 256 characters. Note: See documentation for details. */
  private String lastName;

  /**
   * The mobile phone number. Maximum length: 32 characters. Note: See documentation for details.
   */
  private String mobileNo;

  /**
   * The country or region code. Maximum length: 8 characters. Note: See documentation for details.
   */
  private String country;

  /** The state or province. Maximum length: 128 characters. Note: See documentation for details. */
  private String state;

  /** The city. Maximum length: 256 characters. Note: See documentation for details. */
  private String city;

  /** The address. Maximum length: 1024 characters. Note: See documentation for details. */
  private String address;

  /**
   * The detailed address information. Maximum length: 2048 characters. Note: See documentation for
   * details.
   */
  private String addressDetail;

  /** The ZIP or postal code. Maximum length: 32 characters. Note: See documentation for details. */
  private String zipcode;

  /** The shipping name. Maximum length: 512 characters. Note: See documentation for details. */
  private String shippingName;

  /** The shipping phone. Maximum length: 32 characters. Note: See documentation for details. */
  private String shippingPhone;

  /** The shipping country. Maximum length: 8 characters. Note: See documentation for details. */
  private String shippingCountry;

  /** The shipping state. Maximum length: 128 characters. Note: See documentation for details. */
  private String shippingState;

  /** The shipping city. Maximum length: 256 characters. Note: See documentation for details. */
  private String shippingCity;

  /** The shipping address. Maximum length: 1024 characters. Note: See documentation for details. */
  private String shippingAddress;

  /**
   * The shipping address detail. Maximum length: 2048 characters. Note: See documentation for
   * details.
   */
  private String shippingAddressDetail;

  /** The shipping zip code. Maximum length: 32 characters. Note: See documentation for details. */
  private String shippingZipCode;

  /** The description. Maximum length: 1024 characters. Note: See documentation for details. */
  private String description;

  /**
   * The 3-letter currency code that follows the ISO 4217 standard. Maximum length: 8 characters.
   * Note: See documentation for details.
   */
  private String currency;

  /**
   * The preferred language or locale settings. Maximum length: 256 characters. Note: See
   * documentation for details.
   */
  private String preferredLocales;

  /**
   * The default payment method token. Maximum length: 64 characters. Note: See documentation for
   * details.
   */
  private String defaultPaymentMethod;

  /** The current status. Maximum length: 16 characters. Note: See documentation for details. */
  private String status;

  /**
   * The customer ID in the merchant system. Maximum length: 32 characters. Note: See documentation
   * for details.
   */
  private String referenceCustomerId;

  /** Custom metadata for special use cases. Note: See documentation for details. */
  private Map<String, String> metadata;
}
