/*
 * v1_billing_price_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Amount;
import com.alipay.global.api.model.ams.RecurringSettings;
import com.alipay.global.api.model.ams.Tier;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayPriceInquireDetailsResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayPriceInquireDetailsResponse extends AlipayResponse {

  /** System-generated price ID Returned only when result.resultCode is SUCCESS. */
  private String priceId;

  /** Associated product ID Returned only when result.resultCode is SUCCESS. */
  private String productId;

  /**
   * Price name. O - May be null in the response when the value is not set Returned only when
   * result.resultCode is SUCCESS.
   */
  private String name;

  /**
   * Pricing model type. Always returned. Enum: PER_UNIT/TIERED. See Section 4.1.3 Create Price
   * request for full behavioral descriptions and Section 6.11 for pricing model semantics Returned
   * only when result.resultCode is SUCCESS.
   */
  private String pricingModel;

  /**
   * Usage type. O - May be null in the response when the value is not set Returned only when
   * result.resultCode is SUCCESS.
   */
  private String usageType;

  /**
   * Price-level unit label. O - May be null in the response when the value is not set Returned only
   * when result.resultCode is SUCCESS.
   */
  private String unitLabel;

  /**
   * External meter reference. O - May be null in the response when the value is not set Returned
   * only when result.resultCode is SUCCESS.
   */
  private String meterId;

  private Amount unitAmount;

  private RecurringSettings recurring;

  /**
   * Price active status. true&#x3D;active, false&#x3D;deactivated. Cannot be null Returned only
   * when result.resultCode is SUCCESS.
   */
  private Boolean active;

  /**
   * Included quantity for package pricing. O - May be null in the response when the value is not
   * set Returned only when result.resultCode is SUCCESS.
   */
  private Long includedQuantity;

  /**
   * Tiered pricing mode. O - May be null in the response when the value is not set Returned only
   * when result.resultCode is SUCCESS.
   */
  private String tiersMode;

  /**
   * Tier definitions. O - May be null in the response when the value is not set Returned only when
   * result.resultCode is SUCCESS.
   */
  private List<Tier> tiers;

  /**
   * Custom key-value metadata. O - May be null in the response when the value is not set The value
   * must be a valid JSON object string. Returned only when result.resultCode is SUCCESS.
   */
  private String metadata;

  /** ISO 8601 creation timestamp Returned only when result.resultCode is SUCCESS. */
  private String createdAt;

  /**
   * ISO 8601 deactivation timestamp. O - Returned when price has been deactivated
   * (active&#x3D;false); absent when price is active Returned only when result.resultCode is
   * SUCCESS.
   */
  private String deactivatedAt;

  /**
   * ISO 8601 last update timestamp. O - May be null in the response when the value is not set
   * Returned only when result.resultCode is SUCCESS.
   */
  private String updatedAt;

  /**
   * Whether this price is the default price for the product. When true, this price is the primary
   * price shown for the product Returned only when result.resultCode is SUCCESS.
   */
  private Boolean defaultPrice;
}
