/*
 * v1_billing_subscription_create
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.BillingDiscount;
import com.alipay.global.api.model.ams.SubscriptionItem;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayBillingSubscriptionCreateResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayBillingSubscriptionCreateResponse extends AlipayResponse {

  /** Idempotency key echo-back. Not null Returned only when result.resultCode is SUCCESS. */
  private String subscriptionRequestId;

  /** Created subscription ID. Not null Returned only when result.resultCode is SUCCESS. */
  private String subscriptionId;

  /**
   * The customer this subscription belongs to. Not null Returned only when result.resultCode is
   * SUCCESS.
   */
  private String customerId;

  /**
   * ID of the draft Invoice created alongside the subscription. Returned when subscription creation
   * generates an invoice (i.e., non-zero amount or trial with invoice). Can be null Returned only
   * when result.resultCode is SUCCESS.
   */
  private String invoiceId;

  /**
   * Subscription status after creation. Possible values at creation: INCOMPLETE (first payment
   * pending), TRIALING (trial configured). ACTIVE can only appear after Step 2
   * (&#x60;payments/pay&#x60;) succeeds and is never returned at creation (2026-08-06 code-verified
   * darksite audit). Not null Returned only when result.resultCode is SUCCESS.
   */
  private String status;

  /**
   * Billing period start. ISO 8601 with timezone offset. Not null Returned only when
   * result.resultCode is SUCCESS.
   */
  private String currentPeriodStart;

  /**
   * Billing period end. ISO 8601 with timezone offset. Not null Returned only when
   * result.resultCode is SUCCESS.
   */
  private String currentPeriodEnd;

  /**
   * Billing cycle anchor - the reference point all future billing periods are measured from.
   * System-derived, not merchant-writable (it was withdrawn from the request; see the request
   * table). Derivation: without a trial -&gt; the subscription creation timestamp (NOW); with a
   * trial -&gt; the trial end date (&#x60;trialEnd&#x60;), so the first paid cycle begins when the
   * trial ends. The anchor always describes the full, uncapped cycle - setting &#x60;cancelAt&#x60;
   * inside the first period shortens &#x60;currentPeriodEnd&#x60; but leaves
   * &#x60;billingCycleAnchor&#x60; unchanged. ISO 8601 with timezone offset. Not null Returned only
   * when result.resultCode is SUCCESS.
   */
  private String billingCycleAnchor;

  /** Trial start. ISO 8601 with timezone offset Returned only when result.resultCode is SUCCESS. */
  private String trialStart;

  /** Trial end. ISO 8601 with timezone offset Returned only when result.resultCode is SUCCESS. */
  private String trialEnd;

  /** Scheduled cancellation timestamp Returned only when result.resultCode is SUCCESS. */
  private String cancelAt;

  /**
   * Subscription description echo-back. No HTML tags Returned only when result.resultCode is
   * SUCCESS.
   */
  private String description;

  /** Collection method echo-back. Not null Returned only when result.resultCode is SUCCESS. */
  private String collectionMethod;

  /** Days until invoice due Returned only when result.resultCode is SUCCESS. */
  private Integer daysUntilDue;

  /**
   * The created subscription items, one for each request &#x60;priceItems&#x60; entry. A successful
   * response contains at most 20 items.
   */
  private List<SubscriptionItem> subscriptionItems;

  /**
   * Discount preference echo-back from request - at most 1 item, matching the request limit. Not
   * Antom-generated data - echoed as provided by merchant in request Returned only when
   * result.resultCode is SUCCESS.
   */
  private List<BillingDiscount> discounts;

  /** Subscription notification URL echo-back Returned only when result.resultCode is SUCCESS. */
  private String subscriptionNotifyUrl;
}
