/*
 * v1_billing_invoice_create
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayInvoiceCreateResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInvoiceCreateResponse extends AlipayResponse {

  /**
   * System-generated invoice ID. Also returned for a persisted invoice on BIZ_REPEATED_SUBMIT; use
   * it to reconcile the existing invoice.
   */
  private String invoiceId;

  /**
   * Echo-back of the merchant-supplied idempotency key from the request. Enables merchant-side
   * correlation between request and response. Cannot be null. Returned only when result.resultCode
   * is SUCCESS.
   */
  private String invoiceRequestId;

  /**
   * Invoice status: DRAFT, OPEN for a positive issued total, or PAID for zero-total issuance. Also
   * returned with the persisted invoice on BIZ_REPEATED_SUBMIT.
   */
  private String status;

  /**
   * Hosted invoice URL returned for OPEN and zero-total PAID issuance, even when includePaymentLink
   * is false. Absent for DRAFT creation.
   */
  private String hostedInvoiceUrl;

  /**
   * Email send status. Returned only when &#x60;autoSend&#x3D;true&#x60; in the request. Enum
   * values: &#x60;SENT&#x60; - email dispatched successfully; &#x60;FAILED&#x60; - email dispatch
   * failed (retry allowed). Can be null (when &#x60;autoSend&#x3D;false&#x60; or absent). Returned
   * only when result.resultCode is SUCCESS.
   */
  private String sendStatus;
}
