/*
 * v1_meter_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Meter;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayMeterInquireListResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayMeterInquireListResponse extends AlipayResponse {

  /** The meters. Note: See documentation for details. */
  private List<Meter> meters;
}
