/*
 * v1_billing_subscription_resume
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayBillingSubscriptionResumeResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayBillingSubscriptionResumeResponse extends AlipayResponse {

  /** The subscription ID. Maximum length: 64 characters. */
  private String subscriptionId;

  /** The current status. Maximum length: 20 characters. */
  private String status;

  /** The billing cycle anchor. Note: See documentation for details. */
  private String billingCycleAnchor;

  /**
   * The proration invoice id. Maximum length: 64 characters. Note: See documentation for details.
   */
  private String prorationInvoiceId;

  /** The proration date. Note: See documentation for details. */
  private String prorationDate;
}
