/*
 * v1_billing_invoice_void
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayInvoiceVoidResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInvoiceVoidResponse extends AlipayResponse {

  /**
   * Invoice ID that was voided (echo-back of request). Cannot be null. Returned only when
   * result.resultCode is SUCCESS.
   */
  private String invoiceId;

  /**
   * New invoice status after void: &#x60;VOID&#x60;. The invoice is now in a terminal cancelled
   * state and cannot be modified or paid. Cannot be null. Returned only when result.resultCode is
   * SUCCESS.
   */
  private String status;

  /**
   * ISO 8601 timestamp of when the invoice was voided (e.g.,
   * &#x60;2026-05-10T09:15:00+00:00&#x60;). This is the official time the invoice entered the VOID
   * state. Cannot be null. Returned only when result.resultCode is SUCCESS.
   */
  private String voidedAt;

  /**
   * Echo-back of the &#x60;invoiceNote&#x60; provided in the request, if any. The note is stored in
   * the &#x60;invoiceNotes&#x60; array in the invoice metadata with &#x60;action&#x3D;void&#x60;.
   * Can be null (no note provided). Returned only when result.resultCode is SUCCESS.
   */
  private String invoiceNote;
}
