/*
 * v1_billing_receipt_export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayReceiptExportResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayReceiptExportResponse extends AlipayResponse {

  /**
   * MIME type of the generated file. The response returns the MIME type corresponding to the
   * requested format: &#x60;csv&#x60; -&gt; &#x60;text/csv&#x60;, &#x60;xlsx&#x60; -&gt;
   * &#x60;application/vnd.openxmlformats-officedocument.spreadsheetml.sheet&#x60;. Note: the
   * response &#x60;fileFormat&#x60; returns the MIME type, not the request format code. The request
   * accepts &#x60;csv&#x60;/&#x60;xlsx&#x60;. Maximum length: 128 characters. Returned only when
   * result.resultCode is SUCCESS.
   */
  private String fileFormat;

  /**
   * Expiry timestamp of the signed &#x60;fileUrl&#x60; in ISO 8601 format. Maximum length: 29
   * characters. After this time, accessing the URL returns HTTP 403. Returned only when
   * result.resultCode is SUCCESS.
   */
  private String expiresAt;

  /**
   * Signed OSS URL for file download. URL is time-limited; see &#x60;expiresAt&#x60;. After expiry,
   * accessing the URL returns HTTP 403. Maximum length: 2048 characters. Returned only when
   * result.resultCode is SUCCESS.
   */
  private String fileUrl;

  /** File size in bytes. Returned only when result.resultCode is SUCCESS. */
  private Long fileSize;

  /**
   * Generated file name (e.g., &#x60;receipts_20260401_20260430_1685000000.csv&#x60;). Maximum
   * length: 256 characters. Returned only when result.resultCode is SUCCESS.
   */
  private String fileName;

  /**
   * Execution mode of the export request. The returned value is &#x60;SYNC&#x60;, indicating
   * synchronous export. Maximum length: 8 characters. Returned only when result.resultCode is
   * SUCCESS.
   */
  private String mode;
}
