/*
 * v1_billing_customer_update
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayCustomerUpdateResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCustomerUpdateResponse extends AlipayResponse {

  /**
   * The unique ID assigned by Antom to identify a customer. Maximum length: 64 characters. Note:
   * See documentation for details.
   */
  private String customerId;

  /** The current status. Maximum length: 16 characters. Note: See documentation for details. */
  private String status;

  /**
   * The customer&#39;s phone number (digits only). Replaces deprecated mobileNo. Maximum length: 32
   * characters.
   */
  private String phoneNo;

  /**
   * ISO 3166-1 alpha-2 country code paired with phoneNo. Required when phoneNo is provided. Maximum
   * length: 2 characters.
   */
  private String countryCode;

  /**
   * Invoice recipient email address (independent of account email). Maximum length: 256 characters.
   */
  private String billingEmail;

  /**
   * Shipping recipient first name. Replaces deprecated shippingName. Maximum length: 256
   * characters.
   */
  private String shippingFirstName;

  /**
   * Shipping recipient last name. Replaces deprecated shippingName. Maximum length: 256 characters.
   */
  private String shippingLastName;

  /** ISO 3166-1 alpha-2 country code paired with shippingPhone. Maximum length: 8 characters. */
  private String shippingCountryCode;
}
