/*
 * v1_billing_subscription_update
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.billing;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.BillingSubscriptionUpdatePauseCollection;
import com.alipay.global.api.model.ams.BillingSubscriptionUpdateTrialSettings;
import com.alipay.global.api.model.ams.SubscriptionItem;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayBillingSubscriptionUpdateResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayBillingSubscriptionUpdateResponse extends AlipayResponse {

  /** The subscription ID. Maximum length: 64 characters. */
  private String subscriptionId;

  /** The current status. Maximum length: 20 characters. */
  private String status;

  /** The billing cycle anchor. Note: See documentation for details. */
  private String billingCycleAnchor;

  private BillingSubscriptionUpdatePauseCollection pauseCollection;

  private BillingSubscriptionUpdateTrialSettings trialSettings;

  /** The subscription items. Note: See documentation for details. */
  private List<SubscriptionItem> subscriptionItems;

  /**
   * The proration invoice id. Maximum length: 64 characters. Note: See documentation for details.
   */
  private String prorationInvoiceId;

  /** The credit note ID. Maximum length: 64 characters. Note: See documentation for details. */
  private String creditNoteId;

  /** The cancel at period end. Note: See documentation for details. */
  private Boolean cancelAtPeriodEnd;

  /** The canceled at. Note: See documentation for details. */
  private String canceledAt;

  /** The proration date. Note: See documentation for details. */
  private String prorationDate;
}
