/*
 * marketplace_inquireBalance
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** AccountBalance */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AccountBalance {

  /** The balance account number. More information: Maximum length: 32 characters */
  private String accountNo;

  /**
   * The currency associated with the balance account. The value of this parameter is a 3-letter
   * currency code that follows the ISO 4217 standard. More information: Maximum length: 3
   * characters
   */
  private String currency;

  private Amount availableBalance;

  private Amount frozenBalance;

  private Amount totalBalance;
}
