/*
 * v1_meter_creditGrant_void
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** Applicability */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Applicability {

  /**
   * The applicability scope. Valid values are ALL and SPECIFIC. ALL applies the Credit Grant to all
   * eligible Prices that use the same currency as the Grant and omits priceIds; SPECIFIC applies it
   * only to the Prices specified by priceIds. Maximum length: 8 characters.
   */
  private String scope;

  /**
   * The Price IDs that the Credit Grant applies to. Required when scope is SPECIFIC and values must
   * be unique; omitted when scope is ALL. Maximum size: 64 elements. Maximum length per item: 64
   * characters.
   */
  private List<String> priceIds;
}
