/*
 * v1_billing_promotionCode_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Array */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Array {

  /** The promotion code ID. Maximum length: 64 characters. */
  private String promotionCodeId;

  /** The code. Maximum length: 128 characters. */
  private String code;

  /** The current status. Maximum length: 16 characters. Note: See documentation for details. */
  private String status;

  /** The max redemptions. */
  private Integer maxRedemptions;

  /** The redeemed count. */
  private Integer redeemedCount;

  /** The expiry time. Note: See documentation for details. */
  private String expiryTime;

  /** The create time. */
  private String createTime;
}
