/*
 * marketplace_register
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/** Gets or Sets AssociationType */
public enum AssociationType {
  LEGAL_REPRESENTATIVE("LEGAL_REPRESENTATIVE"),

  UBO("UBO"),

  CONTACT("CONTACT"),

  DIRECTOR("DIRECTOR"),

  AUTHORIZER("AUTHORIZER"),

  BOARD_MEMBER("BOARD_MEMBER");

  private String value;

  AssociationType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static AssociationType fromValue(String value) {
    for (AssociationType b : AssociationType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
