/*
 * marketplace_submitAttachment
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/** Gets or Sets AttachmentType */
public enum AttachmentType {
  SIGNATURE_AUTHORIZATION_LETTER("SIGNATURE_AUTHORIZATION_LETTER"),

  ARTICLES_OF_ASSOCIATION("ARTICLES_OF_ASSOCIATION"),

  LOGO("LOGO"),

  AUTHORIZER_SIGNATURE_CONFIRMATION_LETTER("AUTHORIZER_SIGNATURE_CONFIRMATION_LETTER"),

  ASSOCIATION_ARTICLE("ASSOCIATION_ARTICLE"),

  FINANCIAL_REPORT("FINANCIAL_REPORT"),

  OWNERSHIP_STRUCTURE_PIC("OWNERSHIP_STRUCTURE_PIC"),

  ADDRESS_PROOF("ADDRESS_PROOF"),

  UBO_PROVE("UBO_PROVE"),

  ENTERPRISE_REGISTRATION("ENTERPRISE_REGISTRATION"),

  LICENSE_INFO("LICENSE_INFO"),

  ID_CARD("ID_CARD"),

  PASSPORT("PASSPORT"),

  DRIVING_LICENSE("DRIVING_LICENSE"),

  CPF("CPF"),

  CNPJ("CNPJ");

  private String value;

  AttachmentType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static AttachmentType fromValue(String value) {
    for (AttachmentType b : AttachmentType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
