/*
 * authorizations_consult
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/**
 * The subscription signing-page snapshots. Provide a non-empty object and subscribeTplType for
 * periodic signing; other fields are required only for their documented action/template. The four
 * snapshot fields remain serialized JSON strings, not the shared SubscriptionInfo resource. Do not
 * put baseAmount or offsetAmount inside a snapshot. Null and empty values are invalid when a field
 * is supplied.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AuthorizationConsultSubscriptionParams {

  /**
   * Required when directDebitInfo is provided for periodic signing. Null, empty and blank values
   * are invalid. CREATE maps to CREATE or SEAT_CREATE; TRIAL to TRIAL; UPDATE to UPGRADE,
   * SEAT_INCREASE or SEAT_DECREASE; DOWNGRADE to DOWNGRADE; REVERT_CANCEL to REVERT_CANCEL. Use
   * only enabled action/template combinations. Allowed values: CREATE, TRIAL, UPGRADE, DOWNGRADE,
   * SEAT_CREATE, SEAT_INCREASE, SEAT_DECREASE, REVERT_CANCEL. The subscription page template. It
   * must match the signing action and the enabled channel capability.
   */
  private String subscribeTplType;

  /**
   * A serialized JSON object string, not a nested JSON object. Its fields retain camelCase: title,
   * price, period, periodCount, paymentDay, currentPeriodStart, currentPeriodEnd, nextPaymentDate,
   * discountName, discountAmount, labelName and quantity. Prices and discounts are CNY yuan
   * strings; periodCount is a positive integer string; dates use YYYY-MM-DD. Populate only the
   * fields required by the selected page block using the actual subscription data. Provide when
   * creation, promotion or trial requires a first-period/trial block. Ordinary CREATE includes
   * title, price, period, periodCount, currentPeriodStart and nextPaymentDate. Do not require this
   * block for updates that use original and target snapshots.
   */
  private String firstSubscriptionInfo;

  /**
   * A serialized JSON array string, not a JSON array. Each element uses the same page-snapshot
   * fields described for firstSubscriptionInfo. Provide only for enabled scenarios with different
   * first and subsequent prices or periods; omit for ordinary same-price CREATE. Preserve camelCase
   * keys and actual phase prices and dates.
   */
  private String followSubscriptionInfos;

  /**
   * A serialized JSON object string, not a nested JSON object. Its fields retain camelCase: title,
   * price, period, periodCount, paymentDay, currentPeriodStart, currentPeriodEnd, nextPaymentDate,
   * discountName, discountAmount, labelName and quantity. Prices and discounts are CNY yuan
   * strings; periodCount is a positive integer string; dates use YYYY-MM-DD. Populate only the
   * fields required by the selected page block using the actual subscription data. Required when
   * upgrade, downgrade, seat increase or seat decrease displays the original subscription. Omit for
   * creation or trial. Use the original plan and actual current-period dates.
   */
  private String originSubscriptionInfo;

  /**
   * A serialized JSON object string, not a nested JSON object. Its fields retain camelCase: title,
   * price, period, periodCount, paymentDay, currentPeriodStart, currentPeriodEnd, nextPaymentDate,
   * discountName, discountAmount, labelName and quantity. Prices and discounts are CNY yuan
   * strings; periodCount is a positive integer string; dates use YYYY-MM-DD. Populate only the
   * fields required by the selected page block using the actual subscription data. Required when
   * upgrade, downgrade, seat increase, seat decrease or restoration displays the target
   * subscription. Use the target plan and next payment date consistent with the authorization
   * rules.
   */
  private String targetSubscriptionInfo;

  /**
   * Provide the page-summary next payment date for update or restoration when required by the
   * template. Format: YYYY-MM-DD. This outer field is distinct from the date inside each snapshot;
   * dates for the same payment plan must agree.
   */
  private String nextPaymentDate;

  /**
   * Provide when a period-end change needs to display the current subscription or period expiration
   * date. Format: YYYY-MM-DD. It is not the signing request expiration time and does not replace
   * agreement-state validation.
   */
  private String expireAt;

  /**
   * Provide for a personal upgrade when the page requires the amount before offsetting the
   * remaining subscription value. Use a CNY yuan string with two decimal places. This field is
   * outside the snapshot strings.
   */
  private String baseAmount;

  /**
   * Provide for a personal upgrade when the page requires the remaining-value offset. Use a CNY
   * yuan string with two decimal places. The upgrade payment difference is baseAmount minus
   * offsetAmount; consult does not execute that payment. This field is outside the snapshot
   * strings.
   */
  private String offsetAmount;

  /**
   * Provide only when a separate deduction name is needed; otherwise omit. It must agree with the
   * displayed service name. Omission uses existing channel display behavior without adding an SDK
   * default.
   */
  private String deductName;

  /**
   * Provide only when a separate deduction description is needed; otherwise omit. It must agree
   * with the displayed seat or billing information. Omission does not add an SDK default.
   */
  private String deductDesc;
}
