/*
 * authorizations_consult
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/**
 * The service information displayed on the signing page. A non-empty object with
 * subMerchantServiceName is required for periodic signing.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AuthorizationConsultSubMerchant {

  /**
   * Required when directDebitInfo is provided for periodic signing. Null, empty and blank values
   * are invalid. The actual customer-facing service name displayed on the signing page.
   */
  private String subMerchantServiceName;

  /**
   * Provide when seat or billing information must be displayed to the user; otherwise omit. Use
   * accurate customer-facing seat/billing information, not unrelated personal information. Null or
   * blank values are invalid.
   */
  private String subMerchantServiceDescription;
}
