/*
 * authorizations_consult
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/**
 * Use only for periodic signing when customerBelongsTo is ALIPAY_CN and scopes includes
 * AGREEMENT_PAY. Omit for other requests. When directDebitInfo is omitted, existing request
 * validation, authState semantics, routing and responses remain unchanged. This endpoint-scoped
 * object is not the Pay metadata extension. All fields except oriAgreementNo are required when this
 * object is supplied; oriAgreementNo follows its action-specific rule. Do not send undeclared
 * fields, automatic-renewal specifiedDeductRuleParams, or internal
 * appId/notifyUrl/externalAgreementNo/signNotifyUrl fields. No default product, scene or action is
 * inferred.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AuthorizationConsultDirectDebitInfo {

  /**
   * Required when directDebitInfo is provided for periodic signing. Null, empty and blank values
   * are invalid. Maximum length: 64 characters. Send CYCLE_PAY_AUTH; do not replace it with the
   * channel product code. Allowed values: CYCLE_PAY_AUTH. The periodic-signing API product
   * selector. The service maps it to the channel signing product GENERAL_WITHHOLDING.
   */
  private String channelProductCode;

  /**
   * Required when directDebitInfo is provided for periodic signing. Null, empty and blank values
   * are invalid. Maximum length: 64 characters. Allowed values: CYCLE_PAY_AUTH_P. The Alipay
   * periodic-signing authorization product.
   */
  private String personalProductCode;

  /**
   * Required when directDebitInfo is provided for periodic signing. Null, empty and blank values
   * are invalid. Production uses INDUSTRY|SUBSCRIPTION_DEFAULT_SCENE. Test environments use only
   * explicitly configured test scenes; do not use a test scene in production.
   */
  private String signScene;

  private AuthorizationAccessParams accessParams;

  private PeriodRuleParams periodRuleParams;

  private AuthorizationConsultPassBackParams passBackParams;

  private AuthorizationConsultSubscriptionParams subscriptionParams;

  private AuthorizationConsultSubMerchant subMerchant;

  /**
   * Required when directDebitInfo is provided for periodic signing. Null, empty and blank values
   * are invalid. A signing action, distinct from the page template and not a passBackParams
   * property. Allowed values: CREATE, TRIAL, UPDATE, DOWNGRADE, REVERT_CANCEL. The subscription
   * signing action. Supported enum values do not imply that every action is enabled in production.
   */
  private String subscribeType;

  /**
   * Required for UPDATE, DOWNGRADE and REVERT_CANCEL; omit for CREATE and TRIAL. Supply the
   * original Antom Alipay authorization accessToken, not a raw channel agreement number. The
   * service resolves it within the current merchant and maps it to the channel agreement. Do not
   * log the token. Null and blank values are invalid.
   */
  private String oriAgreementNo;
}
