/*
 * v1_meter_creditGrant_void
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** AvailableAmount */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AvailableAmount {

  /**
   * The 3-letter currency code that follows the ISO 4217 standard. Maximum length: 3 characters.
   */
  private String currency;

  /**
   * The value of the amount as a positive integer in the smallest currency unit. Note: See
   * documentation for details.
   */
  private String value;
}
