/*
 * v1_billing_subscription_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** BillingSubscriptionPriceItem */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BillingSubscriptionPriceItem {

  /** The end of the current billing period in ISO 8601 format. */
  private String currentPeriodEnd;

  /** The start of the current billing period in ISO 8601 format. */
  private String currentPeriodStart;

  private Amount itemAmount;

  /** The subscription item ID. Maximum length: 64 characters. */
  private String itemId;

  /** The display nickname of the price. */
  private String nickname;

  /** The price ID. Maximum length: 64 characters. */
  private String priceId;

  /** The price type, such as RECURRING or ONE_TIME. */
  private String priceType;

  /** The pricing model. Valid values are PER_UNIT and TIERED. */
  private String pricingModel;

  /** The associated product ID. Maximum length: 64 characters. */
  private String productId;

  /** The associated product name. */
  private String productName;

  /** The quantity of this subscription item. */
  private Integer quantity;

  /** The recurring interval. Valid values include DAY, WEEK, MONTH, and YEAR. */
  private String recurringInterval;

  /** The number of recurring intervals in each billing period. */
  private Integer recurringIntervalCount;

  private Amount unitAmount;

  /** The usage type. Valid values include LICENSED and METERED. */
  private String usageType;
}
