/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** BillingTrialSettings */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BillingTrialSettings {

  /**
   * Relative trial duration in days. Value range: 1-365. Exactly one of &#x60;trialPeriodDays&#x60;
   * and &#x60;trialEnd&#x60; must be provided when trial settings are used.
   */
  private Integer trialPeriodDays;

  /**
   * Absolute trial end time in ISO 8601 format with a timezone offset. Exactly one of
   * &#x60;trialPeriodDays&#x60; and &#x60;trialEnd&#x60; must be provided when trial settings are
   * used.
   */
  private String trialEnd;

  /**
   * Behavior when the trial ends without an available payment method. Valid values are CANCEL and
   * PAUSE.
   */
  private String trialEndBehavior;
}
