/*
 * v1_billing_subscription_update
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** BillingSubscriptionStatusChange */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BillingSubscriptionStatusChange {

  /**
   * The subscription status change action. The currently supported value is PAUSE, which pauses
   * payment collection and changes the subscription status from ACTIVE to PAUSED. To reactivate a
   * paused subscription, call the resume subscription API. Maximum length: 10 characters.
   */
  private String action;
}
