/*
 * v1_billing_subscription_update
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** BillingSubscriptionCancellationDetails */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BillingSubscriptionCancellationDetails {

  /**
   * Structured cancellation feedback. Recommended values include TOO_EXPENSIVE, UNUSED,
   * MISSING_FEATURES, TOO_COMPLEX, SWITCHED_SERVICE, LOW_QUALITY, CUSTOMER_SERVICE, and OTHER.
   * Other values are accepted. Maximum length: 64 characters.
   */
  private String feedback;

  /**
   * Additional cancellation details. Do not include personally identifiable information. Maximum
   * length: 500 characters.
   */
  private String comment;
}
