/*
 * vaults_vaultPaymentMethod
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** BrowserInfo */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BrowserInfo {

  /** The accept header of the user&#39;s browser */
  private String acceptHeader;

  /** Indicates whether the user&#39;s browser is able to run Java */
  private Boolean javaEnabled;

  /** Indicates whether the user&#39;s browser is able to run Java */
  private Boolean javaScriptEnabled;

  /** The language of the user&#39;s browser */
  private String language;

  /** The user agent of the user&#39;s browser */
  private String userAgent;
}
