/*
 * marketplace_register
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** BusinessInfo */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BusinessInfo {

  /**
   * mcc String The merchant category code (MCC). See MCC list to check valid values. More
   * information: Maximum length: 32 characters
   */
  private String mcc;

  /**
   * The list of merchant websites. The information is used to verify the company&#39;s legal status
   * and ensure the company complies with regulatory requirements. Specify this parameter when the
   * value of merchantInfo.company.registeredAddress.region is BR. More information: Maximum size:
   * 10 elements
   */
  private List<WebSite> websites;

  /**
   * The English name of the company. Specify this parameter when the value of
   * merchantInfo.company.registeredAddress.region is JP. More information: Maximum length: 256
   * characters
   */
  private String englishName;

  /**
   * The customer-facing business name. Consider user interface limitations when choosing this name.
   * More information: Maximum length: 256 characters
   */
  private String doingBusinessAs;

  /**
   * The country where your primary sales activities take place. The value of this parameter is a
   * 2-letter country or region code based on the ISO 3166 Country Codes standard. Specify this
   * parameter when the value of merchantInfo.company.registeredAddress.region is US. More
   * information: Maximum length: 2 characters
   */
  private String mainSalesCountry;

  /**
   * The App name. Specify this parameter when the value of paymentMethodType is TRUEMONEY. More
   * information: Maximum length: 256 characters
   */
  private String appName;

  /**
   * A clear and detailed description of the product or service. Specify this parameter when the
   * value of paymentMethodType is TRUEMONEY. More information: Maximum length: 256 characters
   */
  private String serviceDescription;
}
