/*
 * aba-inquireCardSensitiveInfo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Map;
import lombok.*;

/**
 * The card detail information returned by inquireCardDetail, excluding the interface-level result.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CardDetail {

  /** Card asset Id. */
  private String assetId;

  /** User-defined card nickname, designed to help users manage multiple cards more conveniently. */
  private String cardNickName;

  /**
   * Card Status: Represents the current state of the card. Possible values include: ACTIVE: The
   * card is active and can be used normally. FROZEN: The card has been frozen and cannot be used
   * temporarily. CANCEL: The card has been canceled and is no longer valid.
   */
  public enum CardStatusEnum {
    ACTIVE("ACTIVE"),

    FROZEN("FROZEN"),

    CANCEL("CANCEL");

    private String value;

    CardStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CardStatusEnum fromValue(String value) {
      for (CardStatusEnum b : CardStatusEnum.values()) {
        if (b.value.equals(value) || b.name().equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  /**
   * Card Status: Represents the current state of the card. Possible values include: ACTIVE: The
   * card is active and can be used normally. FROZEN: The card has been frozen and cannot be used
   * temporarily. CANCEL: The card has been canceled and is no longer valid.
   */
  private CardStatusEnum cardStatus;

  /** Masked card number. */
  private String maskedCardNo;

  /**
   * Card Brand: Indicates the brand or network of the card. Possible value: MASTERCARD: The card is
   * part of the Mastercard network.
   */
  public enum CardBrandEnum {
    MASTERCARD("MASTERCARD");

    private String value;

    CardBrandEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CardBrandEnum fromValue(String value) {
      for (CardBrandEnum b : CardBrandEnum.values()) {
        if (b.value.equals(value) || b.name().equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  /**
   * Card Brand: Indicates the brand or network of the card. Possible value: MASTERCARD: The card is
   * part of the Mastercard network.
   */
  private CardBrandEnum cardBrand;

  /** Datetime UTC time: 2018-10-31T00:00:00+0800. ISO 8601 */
  private String createdTime;

  /** Datetime UTC time: 2018-10-31T00:00:00+0800. ISO 8601 */
  private String updatedTime;

  /** Purpose of the card */
  private String purpose;

  /** Note information of card application */
  private String note;

  /**
   * Customer metadata in key-value format. - Key max length: 32 - Value max length: 128 - Max
   * number of keys: 30 - Total JSON string max length: 3096
   */
  private Map<String, String> metadata;

  private AuthorizationControl authorizationControl;

  private CardholderInfo cardholderinfo;
}
