/*
 * vaults_inquireVaulting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** CardPaymentMethodDetail */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CardPaymentMethodDetail {

  /**
   * The token of the card. The value of this parameter is used by paymentMethodId in the pay
   * (Checkout Payment) API when initiating payments. More information: Maximum length: 2048
   * characters
   */
  private String cardToken;

  private String cardNo;

  private CardBrand brand;

  private CardBrand selectedCardBrand;

  private String cardIssuer;

  private String countryIssue;

  private UserName instUserName;

  private String expiryYear;

  private String expiryMonth;

  private Address billingAddress;

  private String mask;

  private String last4;

  private String paymentMethodDetailMetadata;

  /**
   * The masked card number, showing only a few digits and hiding the rest. More information:
   * Maximum length: 64 characters
   */
  private String maskedCardNo;

  private String fingerprint;

  private String authenticationFlow;

  private String funding;

  private String avsResultRaw;

  private String cvvResultRaw;

  private String bin;

  private String issuerName;

  private String issuingCountry;

  private String lastFour;

  private UserName cardholderName;

  private String cvv;

  private String dateOfBirth;

  private String businessNo;

  private String cardPasswordDigest;

  private String cpf;

  private String payerEmail;

  /**
   * The unique ID assigned by the card scheme to identify a transaction. More information: Maximum
   * length: 256 characters
   */
  private String networkTransactionId;

  private Boolean is3DSAuthentication;

  private String request3DS;

  private String scaExemptionIndicator;

  private String enableAuthenticationUpgrade;

  private MpiData mpiData;
}
