/*
 * vaults_inquireVaulting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** CardPaymentMethodDetail */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CardPaymentMethodDetail {

  /** Supported card brands for this payment method */
  private String supportedBrands;

  /**
   * The token of the card. The value of this parameter is used by paymentMethodId in the pay
   * (Checkout Payment) API when initiating payments. More information: Maximum length: 2048
   * characters
   */
  private String cardToken;

  /** The card number. More information: Maximum length: 32 characters */
  private String cardNo;

  private CardBrand brand;

  private CardBrand selectedCardBrand;

  private String cardIssuer;

  private String countryIssue;

  private UserName instUserName;

  /**
   * The year the card expires. Pass in the last two digits of the year number. For example, if the
   * expiration year is 2025, the value of this parameter is 25. More information: Maximum length: 2
   * characters
   */
  private String expiryYear;

  /**
   * The month the card expires. Pass in two digits representing the month. For example, if the
   * expiration month is February, the value of this parameter is 02. More information: Maximum
   * length: 2 characters
   */
  private String expiryMonth;

  private Address billingAddress;

  private String mask;

  private String last4;

  private String paymentMethodDetailMetadata;

  /**
   * The masked card number, showing only a few digits and hiding the rest. More information:
   * Maximum length: 64 characters
   */
  private String maskedCardNo;

  private String fingerprint;

  private String authenticationFlow;

  private String funding;

  private String avsResultRaw;

  private String cvvResultRaw;

  private String bin;

  private String issuerName;

  private String issuingCountry;

  private String lastFour;

  private UserName cardholderName;

  /**
   * The card verification value (CVV), which is also known as a card security code (CSC) or a card
   * verification code (CVC). Note: Specify this parameter when the card issuing bank is in Brazil,
   * Chile, Mexico, or Peru, or the card is a global card. More information: Maximum length: 3
   * characters
   */
  private String cvv;

  /**
   * The date of birth of the cardholder. The value of this parameter is an 8-digit date of birth in
   * the format of YYYY-MM-DD that follows the ISO 8601 standard. For example, 1971-06-07 means the
   * cardholder&#39;s birthday is June 7, 1971. Specify this parameter when all the following
   * conditions are met: The card issuing bank is in Korea. The card is a personal card. More
   * information: Maximum length: 10 characters
   */
  private String dateOfBirth;

  /**
   * The business number of the company that holds the corporate card. The value of this parameter
   * is a 10-digit business number, such as 97XXXXXX11. Specify this parameter when all the
   * following conditions are met: The card issuing bank is in Korea. The card is a corporate card.
   * More information: Maximum length: 10 characters
   */
  private String businessNo;

  /**
   * The first two digits of the card payment password. Note: Specify this parameter when the card
   * issuing bank is in Korea. More information: Maximum length: 2 characters
   */
  private String cardPasswordDigest;

  /**
   * The Cadastro Pessoal de Pessoa Física (CPF) is the tax ID of the Brazilian individual taxpayer.
   * Note: Specify this parameter when the card issuing bank is in Brazil. More information: Maximum
   * length: 11 characters
   */
  private String cpf;

  /**
   * The email address of the payer. Note: Specify this parameter when the card issuing bank is in
   * Brazil, Chile, Mexico, or Peru. More information: Maximum length: 64 characters
   */
  private String payerEmail;

  /**
   * The unique ID assigned by the card scheme to identify a transaction. More information: Maximum
   * length: 256 characters
   */
  private String networkTransactionId;

  /**
   * Indicates whether the transaction authentication type is 3D secure. Specify this parameter when
   * the value of paymentMethodType is CARD.
   */
  private Boolean is3DSAuthentication;

  private String request3DS;

  private String scaExemptionIndicator;

  private String enableAuthenticationUpgrade;

  private MpiData mpiData;
}
