/*
 * aba-inquireCardTransactionEvent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/** Gets or Sets CardTransactionEventFilterType */
public enum CardTransactionEventFilterType {
  AUTH("AUTH"),

  AUTH_CANCEL("AUTH_CANCEL"),

  CAPTURE("CAPTURE"),

  REFUND("REFUND"),

  CHARGEBACK("CHARGEBACK"),

  REPAYMENT("REPAYMENT");

  private String value;

  CardTransactionEventFilterType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CardTransactionEventFilterType fromValue(String value) {
    for (CardTransactionEventFilterType b : CardTransactionEventFilterType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
