/*
 * marketplace_register
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/** Gets or Sets CertificateType */
public enum CertificateType {
  ENTERPRISE_REGISTRATION("ENTERPRISE_REGISTRATION"),

  LICENSE_INFO("LICENSE_INFO"),

  ID_CARD("ID_CARD"),

  PASSPORT("PASSPORT"),

  DRIVING_LICENSE("DRIVING_LICENSE"),

  CPF("CPF"),

  CNPJ("CNPJ");

  private String value;

  CertificateType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CertificateType fromValue(String value) {
    for (CertificateType b : CertificateType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
