/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** CodeDetail */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CodeDetail {

  private CodeValueType codeValueType;

  /**
   * The value of the code. If the value of displayType is set toSMALLIMAGE, MIDDLEIMAGE, or
   * BIGIMAGE, this parameter indicates a plain or Base64-encoded image URL. If the value of
   * displayType is set to TEXT, this parameter indicates a text string. More information: Maximum
   * length: 2048 characters
   */
  private String codeValue;

  private DisplayType displayType;
}
