/*
 * v1_billing_coupon_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** CouponApplicableProduct */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CouponApplicableProduct {

  /** Whether the product can be deleted. */
  private Boolean canDelete;

  /** ISO 8601 timestamp of the latest product update. */
  private String gmtModified;

  /** Number of prices associated with the product. */
  private Integer priceCount;

  /** System-generated product ID. Maximum length: 64 characters. */
  private String productId;

  /** Product display name. */
  private String productName;

  /** Product status. */
  private String status;
}
