/*
 * v1_billing_coupon_create
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** CouponPromotionCode */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CouponPromotionCode {

  /** The system-generated promotion code ID. */
  private String promotionCodeId;

  /** The merchant-supplied or system-generated promotion code string. */
  private String code;

  /** The promotion code status. The value is ACTIVE on creation. */
  private String status;
}
