/*
 * v1_billing_coupon_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Coupon */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Coupon {

  /** System-generated coupon ID. */
  private String couponId;

  /** Coupon display name. */
  private String couponName;

  /**
   * Filter by discount type. Allowed values: &#x60;PERCENT&#x60;, &#x60;AMOUNT&#x60;. If not
   * provided, returns all discount types.
   */
  private String discountType;

  /**
   * Percentage discount (up to 2 decimal places). Returned when &#x60;discountType&#x60; &#x3D;
   * &#x60;PERCENT&#x60;.
   */
  private String percentOff;

  private Amount amountOff;

  /** Redemption expiry time. */
  private String redeemBy;

  /**
   * Filter by coupon status. Allowed values: &#x60;ACTIVE&#x60;, &#x60;INACTIVE&#x60;. If not
   * provided, returns coupons of all statuses.
   */
  private String status;

  /** The maximum redemption count. */
  private Integer maxRedemptions;

  /** The number of times the coupon has been redeemed. */
  private Integer redeemedCount;
}
