/*
 * v1_meter_creditGrant_void
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** CreditGrant */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreditGrant {

  /** The credit grant ID. Maximum length: 64 characters. */
  private String creditGrantId;

  /** The credit grant name. Maximum length: 255 characters. */
  private String creditGrantName;

  /** The unique ID assigned by Antom to identify a customer. Maximum length: 64 characters. */
  private String customerId;

  /** The current status. Maximum length: 8 characters. */
  private String status;

  private Amount amount;

  private AvailableAmount availableAmount;

  private Applicability applicability;

  /** The priority. */
  private Integer priority;

  /** The category. Maximum length: 16 characters. */
  private String category;

  /**
   * The effective date time. Maximum length: 32 characters. Note: See documentation for details.
   */
  private String effectiveDateTime;

  /** The expiry date time. Maximum length: 32 characters. Note: See documentation for details. */
  private String expiryDateTime;

  /** The created date time. Maximum length: 32 characters. */
  private String createdDateTime;

  /** The updated date time. Maximum length: 32 characters. */
  private String updatedDateTime;
}
