/*
 * v1_billing_creditNote_create
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** CreditNoteCreateItem */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreditNoteCreateItem {

  /**
   * The credit note item type. Valid values are INVOICE_LINE_ITEM and CUSTOM_LINE_ITEM. Maximum
   * length: 32 characters.
   */
  private String type;

  /**
   * The invoice item ID. Required when type is INVOICE_LINE_ITEM. Maximum length: 64 characters.
   */
  private String invoiceItemId;

  /**
   * The custom line item description. Required when type is CUSTOM_LINE_ITEM. Maximum length: 256
   * characters.
   */
  private String description;

  /**
   * The quantity to credit. For an INVOICE_LINE_ITEM, provide either quantity or itemAmount, but
   * not both.
   */
  private Integer quantity;

  private Amount unitAmount;

  private Amount itemAmount;
}
