/*
 * v1_meter_creditGrant_void
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** CreditGrant */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreditGrant {

  /** The unique identifier of the Credit Grant. Maximum length: 64 characters. */
  private String creditGrantId;

  /** The merchant-facing name of the Credit Grant. Maximum length: 255 characters. */
  private String creditGrantName;

  /** The Customer that receives the credit. Maximum length: 64 characters. */
  private String customerId;

  /**
   * The Credit Grant status. Valid values are PENDING, ACTIVE, EXPIRED, and VOIDED. VOIDED is the
   * only irreversible terminal state. Maximum length: 8 characters.
   */
  private String status;

  private Amount amount;

  private Amount availableAmount;

  private Applicability applicability;

  /** The application priority from 0 to 100. A lower value has a higher priority. */
  private Integer priority;

  /**
   * The Credit Grant category. Valid values are PREPAID and PROMOTIONAL. Maximum length: 16
   * characters.
   */
  private String category;

  /**
   * The effective time in ISO 8601 UTC format, encoded as a JSON string. Omitted when the Grant is
   * effective immediately. Maximum length: 32 characters.
   */
  private String effectiveDateTime;

  /**
   * The expiration time in ISO 8601 UTC format, encoded as a JSON string. Omitted when the Grant
   * does not expire automatically. Maximum length: 32 characters.
   */
  private String expiryDateTime;

  /**
   * The creation time in ISO 8601 UTC format, encoded as a JSON string. Maximum length: 32
   * characters.
   */
  private String createdDateTime;

  /**
   * The last update time in ISO 8601 UTC format, encoded as a JSON string. Maximum length: 32
   * characters.
   */
  private String updatedDateTime;
}
