/*
 * v1_billing_creditNote_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** CreditNoteItem */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreditNoteItem {

  /** The credit note item ID. Maximum length: 64 characters. */
  private String creditNoteItemId;

  /** The credit note item type. Maximum length: 32 characters. */
  private String type;

  /** The related invoice item ID. Omitted for a custom line item. Maximum length: 64 characters. */
  private String invoiceItemId;

  /** The credit note item description. Maximum length: 256 characters. */
  private String description;

  /** The credited quantity. */
  private Integer quantity;

  private Amount unitAmount;

  private Amount itemAmount;
}
