/*
 * v1_billing_creditNote_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** CreditNoteInquireDetailsItems */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreditNoteInquireDetailsItems {

  /** The data. Maximum length: 100 characters. */
  private List<LineItem> data;

  /** The has more. */
  private Boolean hasMore;
}
