/*
 * v1_billing_customer_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Customer */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Customer {

  /** Filter by exact customer ID (single exact match). */
  private String customerId;

  /** Merchant-supplied idempotency key. */
  private String customerRequestId;

  /** Filter by exact email address match. Maximum length: 256 characters. */
  private String email;

  /** Customer first name. Returned when the field was set. */
  private String firstName;

  /** Customer last name. Returned when the field was set. */
  private String lastName;

  /**
   * Filter by customer status. Allowed values: &#x60;ACTIVE&#x60;, &#x60;DELETED&#x60;. If not
   * provided, returns customers of all statuses.
   */
  private String status;

  /** Invoice recipient email (independent of account email). Returned when the field was set. */
  private String billingEmail;

  /**
   * Filter by billing country codes (ISO 3166-1 alpha-2) using SQL &#x60;IN&#x60; clause. Maximum
   * size: 50 elements.
   */
  private String country;

  /** Customer creation timestamp. */
  private String gmtCreate;
}
