/*
 * vaults_vaultPaymentMethod
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** CustomizedInfo */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CustomizedInfo {

  /** Customized field 1 */
  private String customizedField1;

  /** Customized field 2 */
  private String customizedField2;

  /** Customized field 3 */
  private String customizedField3;

  /** Customized field 4 */
  private String customizedField4;

  /** Customized field 5 */
  private String customizedField5;
}
