/*
 * v1_billing_customer_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Customer */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Customer {

  /** The unique ID assigned by Antom to identify a customer. Maximum length: 64 characters. */
  private String customerId;

  /** The unique ID assigned by a merchant to identify a request. Maximum length: 64 characters. */
  private String customerRequestId;

  /** The email address. Maximum length: 256 characters. Note: See documentation for details. */
  private String email;

  /** The first name. Maximum length: 256 characters. Note: See documentation for details. */
  private String firstName;

  /** The last name. Maximum length: 256 characters. Note: See documentation for details. */
  private String lastName;

  /** The current status. Maximum length: 16 characters. */
  private String status;
}
