/*
 * payments_ inquiryPayment
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Discount */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Discount {

  private String discountTag;

  /**
   * The discount name displayed in the default language. More information: Maximum length: 128
   * characters
   */
  private String discountName;

  private Amount savingsAmount;

  private Amount estimateSavingsAmount;
}
