/*
 * vaults_vaultPaymentMethod
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Env */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Env {

  private TerminalType terminalType;

  private OsType osType;

  private String userAgent;

  /**
   * The token identifier of the device. Note: Specify this parameter if you integrate with the
   * Antom Device Fingerprint client, which is an SDK or JavaScript library that is used to collect
   * device-related information, such as osType, deviceLanguage, deviceId, websiteLanguage, and
   * userAgent. The device-related information helps to increase the accuracy of anti-money
   * laundering and fraud detection, and increase payment success rates. For more information about
   * the Antom Device Fingerprint client, contact Antom Technical Support. More information: Maximum
   * length: 64 characters
   */
  private String deviceTokenId;

  /** Client IP address of the device. */
  private String clientIp;

  private String cookieId;

  /**
   * Extended information. Specify this field if you need to use the extended information. More
   * information: Maximum length: 2048 characters
   */
  private String extendInfo;

  private String storeTerminalId;

  private String storeTerminalRequestTime;

  private BrowserInfo browserInfo;

  /**
   * The color depth of the user&#39;s browser in bits per pixel. The value is obtained by using the
   * browser&#39;s screen.colorDepth property. Valid values are 1, 4, 8, 15, 16, 24, 30, 32, or 48.
   * For example, 8 means 8-bit color depth. More information: Value range: 0 - unlimited
   */
  private String colorDepth;

  /**
   * The screen height of the user&#39;s device in pixels. Note: Specify this parameter if you
   * require risk control. Providing this information helps to increase the accuracy of anti-money
   * laundering and fraud detection, and increase payment success rates. More information: Value
   * range: 1 - unlimited
   */
  private String screenHeight;

  /**
   * The screen width of the user&#39;s device in pixels. Note: Specify this parameter if you
   * require risk control. Providing this information helps to increase the accuracy of anti-money
   * laundering and fraud detection, and increase payment success rates. More information: Value
   * range: 1 - unlimited
   */
  private String screenWidth;

  /**
   * The time difference between UTC time and the local time of the user&#39;s browser, in minutes.
   * The value is obtained by using the getTimezoneOffset() property. For example, if the local time
   * of the user&#39;s browser is UTC+2, the value of this parameter is -120. Note: Specify this
   * parameter if you require risk control. Providing this information helps to increase the
   * accuracy of anti-money laundering and fraud detection, and increase payment success rates. More
   * information: Value range: -720 - 720
   */
  private Integer timeZoneOffset;

  /**
   * The brand of the user&#39;s device. Note: Specify this parameter if you require risk control.
   * Providing this information helps to increase the accuracy of anti-money laundering and fraud
   * detection, and increase payment success rates. More information: Maximum length: 64 characters
   */
  private String deviceBrand;

  /**
   * The model of the user&#39;s device. Note: Specify this parameter if you require risk control.
   * Providing this information helps to increase the accuracy of anti-money laundering and fraud
   * detection, and increase payment success rates. More information: Maximum length: 128 characters
   */
  private String deviceModel;

  /** Device language of the user. */
  private String deviceLanguage;

  /** Device ID of the user. */
  private String deviceId;

  /** Version of the operation system. */
  private String osVersion;
}
