/*
 * vaults_vaultPaymentMethod
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Env */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Env {

  private TerminalType terminalType;

  private OsType osType;

  private String userAgent;

  private String deviceTokenId;

  /**
   * The IP address of the client device. Specify this parameter when one of the following
   * conditions is met: You require risk control. The value of paymentMethodType is CARD. Providing
   * this information helps to increase the accuracy of anti-money laundering and fraud detection,
   * and increase payment success rates. More information: Maximum length: 64 characters
   */
  private String clientIp;

  private String cookieId;

  private String extendInfo;

  private String storeTerminalId;

  private String storeTerminalRequestTime;

  private BrowserInfo browserInfo;

  private String colorDepth;

  private String screenHeight;

  private String screenWidth;

  private Integer timeZoneOffset;

  private String deviceBrand;

  private String deviceModel;

  /**
   * The language of the device where the user places an order. Note: Specify this parameter if you
   * require risk control. Providing this information helps to identify black-market behavior. More
   * information: Maximum length: 32 characters
   */
  private String deviceLanguage;

  /**
   * The unique ID of the device the user places an order with. Note: Specify this parameter if you
   * require risk control. This parameter can be used to build a trusted relationship between users
   * and commonly used devices, thereby reducing risk control interruptions and increasing the
   * payment success rate. More information: Maximum length: 64 characters
   */
  private String deviceId;
}
