/*
 * v1_meter_uploadEvent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Error */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Error {

  /** The index. */
  private Integer index;

  /** The group index. Note: See documentation for details. */
  private Integer groupIndex;

  /** The event name. Maximum length: 128 characters. */
  private String eventName;

  /** The idempotency key. Maximum length: 128 characters. */
  private String idempotencyKey;

  /** The unique ID assigned by Antom to identify a customer. Maximum length: 128 characters. */
  private String customerId;

  /** The error code. Maximum length: 64 characters. */
  private String errorCode;
}
