/*
 * payments_refund
 *       Use this API to initiate a refund against a successful payment. The refund can be full or partial.        A transaction can have multiple refunds as long as the total refund amount is less than or equal to the original transaction amount.         If the refund request is out of the refund window determined in the contract, the refund request will be declined.    Note: Use the same refundRequestId field to retry a refund in case of timeout or when the returned resultStatus is ​U​. The refundRequestId field is designed to be idempotent.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Goods */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Goods {

  /** The unique ID to identify the goods. More information: Maximum length: 64 characters */
  private String referenceGoodsId;

  /** Goods name. More information: Maximum length: 256 characters */
  private String goodsName;

  /**
   * The category of the goods. If the goods have multiple layers for categorization, use slashes
   * between different categories and write the parent category before the subcategory, such as
   * Digital Goods/Digital Vouchers/Food and Beverages. Note: Specify this parameter if you require
   * risk control. Providing this information helps to increase the accuracy of anti-money
   * laundering and fraud detection, and increase payment success rates. More information: Maximum
   * length: 64 characters
   */
  private String goodsCategory;

  private String goodsBrand;

  private Amount goodsUnitAmount;

  /**
   * Quantity of goods. Specify this parameter if you require risk control. Providing this
   * information helps to increase the accuracy of anti-money laundering and fraud detection, and
   * increase payment success rates. More information: Value range: 1 - unlimited
   */
  private String goodsQuantity;

  private String goodsSkuName;

  /**
   * The URL of the website where the user places an order. Specify this parameter if you require
   * risk control. Providing this information helps to identify black-market behavior. More
   * information: Maximum length: 2048 characters
   */
  private String goodsUrl;

  /**
   * The delivery method of the goods. Valid values are: PHYSICAL: indicates that the delivery
   * method is physical delivery. DIGITAL: indicates that the delivery method is digital delivery.
   * Specify this parameter if you require risk control. Providing this information helps to
   * increase the accuracy of anti-money laundering and fraud detection, and increase payment
   * success rates. More information: Maximum length: 32 characters
   */
  private String deliveryMethodType;

  /**
   * The URL of the goods image. When using KLARNA, this value is used to display the goods image in
   * the payment method app and must not exceed 1024 characters.
   */
  private String goodsImageUrl;

  /**
   * The ID of the Price object. One of ​priceId​ or ​referenceGoodsId​ is required. More
   * information: Maximum length: 64 characters
   */
  private String priceId;

  private Amount goodsDiscountAmount;

  /**
   * The maximum end date for the service goods. Applicable when the merchant type is Service (e.g.,
   * online courses, beauty packages). The value follows the ISO 8601 standard format. For example,
   * \&quot;2025-11-27T12:00:01+08:30\&quot;.
   */
  private String goodsEndsOnTime;

  private Goods crossSell;

  /**
   * For createPaymentSession, this is the product tax code used by Antom GlobalTax to classify the
   * goods line. When automatic tax is active, omit it to use the merchant default tax code. Because
   * Goods is a shared SDK model, omit this field in APIs that do not explicitly document support.
   * Maximum length: 64 characters.
   */
  private String taxCode;

  /**
   * For createPaymentSession, this value indicates whether the goods-line price excludes or
   * includes tax. Supported values are EXCLUSIVE and INCLUSIVE. When automatic tax is active, omit
   * it to use the merchant tax behavior settings. Because Goods is a shared SDK model, omit this
   * field in APIs that do not explicitly document support. Maximum length: 16 characters.
   */
  private String taxBehavior;
}
