/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Goods */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Goods {

  /** The unique ID to identify the goods. More information: Maximum length: 64 characters */
  private String referenceGoodsId;

  /** Goods name. More information: Maximum length: 256 characters */
  private String goodsName;

  /**
   * The category of the goods. If the goods have multiple layers for categorization, use slashes
   * between different categories and write the parent category before the subcategory, such as
   * Digital Goods/Digital Vouchers/Food and Beverages. Note: Specify this parameter if you require
   * risk control. Providing this information helps to increase the accuracy of anti-money
   * laundering and fraud detection, and increase payment success rates. More information: Maximum
   * length: 64 characters
   */
  private String goodsCategory;

  private String goodsBrand;

  private Amount goodsUnitAmount;

  /**
   * Quantity of goods. Specify this parameter if you require risk control. Providing this
   * information helps to increase the accuracy of anti-money laundering and fraud detection, and
   * increase payment success rates. More information: Value range: 1 - unlimited
   */
  private String goodsQuantity;

  private String goodsSkuName;

  /**
   * The URL of the website where the user places an order. Specify this parameter if you require
   * risk control. Providing this information helps to identify black-market behavior. More
   * information: Maximum length: 2048 characters
   */
  private String goodsUrl;

  /**
   * The delivery method of the goods. Valid values are: PHYSICAL: indicates that the delivery
   * method is physical delivery. DIGITAL: indicates that the delivery method is digital delivery.
   * Specify this parameter if you require risk control. Providing this information helps to
   * increase the accuracy of anti-money laundering and fraud detection, and increase payment
   * success rates. More information: Maximum length: 32 characters
   */
  private String deliveryMethodType;

  private String goodsImageUrl;

  /**
   * The ID of the Price object. One of ​priceId​ or ​referenceGoodsId​ is required. More
   * information: Maximum length: 64 characters
   */
  private String priceId;
}
