/*
 * marketplace_register
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** Individual */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Individual {

  private UserName name;

  private UserName englishName;

  /**
   * The individual&#39;s date of birth. The information is used to verify the company&#39;s legal
   * status and ensure the company complies with regulatory requirements. Specify this parameter
   * when the value of merchantInfo.company.registeredAddress.region is BR. More information:
   * Maximum length: 32 characters
   */
  private String dateOfBirth;

  private Address placeOfBirth;

  /**
   * The list of certificate information of the individual. The information is used to verify the
   * company&#39;s legal status and ensure the company complies with regulatory requirements.
   * Specify this parameter when the value of merchantInfo.company.registeredAddress.region is BR or
   * US.
   */
  private List<Certificate> certificates;

  /**
   * The nationality of the individual. The value of this parameter is a 2-letter country or region
   * code based on the ISO 3166 Country Codes standard. Specify this parameter when the value of
   * merchantInfo.company.registeredAddress.region is EU, GB, MY, US, or BR. More information:
   * Maximum length: 2 characters
   */
  private String nationality;

  /**
   * A list of contact information. Specify this parameter when the value of
   * merchantInfo.company.registeredAddress.region is JP and the value of
   * merchantInfo.entityAssociations.associationType is LEGAL_REPRESENTATIVE. More information:
   * Maximum size: 10 elements
   */
  private List<Contact> contacts;
}
