/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** InterestFree */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InterestFree {

  /**
   * Issuing banks or financial institutions that offer interest-free installment plans. More
   * information: Maximum length: 128 characters
   */
  private String provider;

  /**
   * The promotion expiration time. More information: The value follows the ISO 8601 standard
   * format. For example, \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String expireTime;

  /** The number of interest-free installments. More information: Value range: 2-unlimited */
  private List<Integer> installmentFreeNums;

  private Amount minPaymentAmount;

  private Amount maxPaymentAmount;

  /**
   * The interest-free percentage. A value of 0 indicates no interest-free, 100% indicates the buyer
   * is completely interest-free, while the value between 0-100% indicates partial interest-free.
   */
  private Integer freePercentage;
}
