/*
 * v1_billing_invoice_update
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** InvoiceAddress */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InvoiceAddress {

  /** Two-letter country code that follows ISO 3166-1 alpha-2. Maximum length: 8 characters. */
  private String country;

  /** State, province, or region. Maximum length: 128 characters. */
  private String state;

  /** City, district, suburb, town, or village. Maximum length: 256 characters. */
  private String city;

  /** Primary address line. Maximum length: 1024 characters. */
  private String address1;

  /** Additional address line. Maximum length: 1024 characters. */
  private String address2;

  /** Postal or ZIP code. Maximum length: 32 characters. */
  private String postalCode;
}
