/*
 * v1_billing_invoice_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** InvoiceNote */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InvoiceNote {

  /** Unique identifier for this note within the array (UUID). Cannot be null. */
  private String noteId;

  /**
   * The actual note content. Provided by the merchant when performing an action on the invoice.
   * Cannot be null.
   */
  private String note;

  /**
   * The action that triggered this note. Allowed values: &#x60;CREATE&#x60; - invoice created;
   * &#x60;UPDATE&#x60; - invoice updated; &#x60;FINALIZE&#x60; - invoice finalized
   * (DRAFT-&gt;OPEN); &#x60;VOID&#x60; - invoice voided; &#x60;MARK_UNCOLLECTIBLE&#x60; - invoice
   * marked uncollectible; &#x60;PAID&#x60; - payment confirmed. Cannot be null.
   */
  private String action;

  /** ISO 8601 timestamp of when the note was created. Cannot be null. */
  private String noteTime;
}
