/*
 * v1_billing_invoice_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Invoice */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Invoice {

  /**
   * System-generated invoice ID. Format: &#x60;inv_&#x60; + 10-char alphanumeric. Cannot be null.
   */
  private String invoiceId;

  /** Associated subscription ID. May be null for standalone manual invoices. Can be null. */
  private String subscriptionId;

  /** Customer ID this invoice belongs to. Cannot be null. */
  private String customerId;

  /**
   * Customer&#39;s first name. Populated from the customer record at invoice creation time.
   * Displayed on merchant portal list view. Can be null.
   */
  private String customerFirstName;

  /**
   * Customer&#39;s last name. Populated from the customer record at invoice creation time.
   * Displayed on merchant portal list view. Can be null.
   */
  private String customerLastName;

  /**
   * Customer&#39;s email address. Populated from the customer record at invoice creation time.
   * Displayed on merchant portal list view. Can be null.
   */
  private String customerEmail;

  /**
   * Invoice creation reason: &#x60;SUBSCRIPTION_CREATION&#x60;,
   * &#x60;SUBSCRIPTION_RECURRENCE&#x60;, &#x60;SUBSCRIPTION_UPDATE&#x60;. Cannot be null.
   */
  private String reason;

  /**
   * Current invoice status: &#x60;DRAFT&#x60;, &#x60;OPEN&#x60;, &#x60;PAID&#x60;,
   * &#x60;UNCOLLECTIBLE&#x60;, &#x60;VOID&#x60;. Cannot be null.
   */
  private String status;

  private Amount totalAmount;

  private Amount paidAmount;

  private Amount remainAmount;

  /**
   * Three-letter ISO currency code in uppercase (e.g., &#x60;\&quot;USD\&quot;&#x60;). The invoice
   * currency. Cannot be null.
   */
  private String currency;

  /** Billing period start timestamp (ISO 8601). Cannot be null. */
  private String periodStart;

  /** Billing period end timestamp (ISO 8601). Cannot be null. */
  private String periodEnd;

  /** Payment due date (ISO 8601). Cannot be null. */
  private String dueDate;

  /** ISO 8601 timestamp of invoice creation. Cannot be null. */
  private String gmtCreate;

  /** ISO 8601 timestamp of last invoice update. Cannot be null. */
  private String gmtUpdate;

  /** Invoice description text. Can be null. */
  private String description;

  /** URL of the generated PDF file for download. Can be null (PDF not yet generated). */
  private String pdfFileUrl;
}
