/*
 * v1_billing_invoice_update
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** InvoiceShipping */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InvoiceShipping {

  private UserName shippingName;

  private InvoiceAddress shippingAddress;

  /**
   * Delivery service provider (e.g., FedEx, UPS, USPS). Characters &#x60;&lt;&#x60;,
   * &#x60;&gt;&#x60;, and &#x60;&amp;&#x60; are not allowed.
   */
  private String shippingCarrier;

  /** Tracking number. */
  private String shippingNumber;

  /** Recipient phone number. */
  private String shippingPhoneNo;

  /** Recipient email address. Must be a valid email format. */
  private String shipToEmail;

  /** The notes. Maximum length: 512 characters. */
  private String notes;

  /** The shipping fee id. Maximum length: 64 characters. */
  private String shippingFeeId;

  private Amount shippingFee;

  /** The shipping description. Maximum length: 256 characters. */
  private String shippingDescription;

  private DeliveryEstimate deliveryEstimate;

  /** The tracking url. Maximum length: 2048 characters. */
  private String trackingUrl;

  /**
   * Shipping method indicator for 3DS risk assessment. Allowed EMVCo values: &#x60;01&#x60;,
   * &#x60;02&#x60;, &#x60;03&#x60;, &#x60;04&#x60;, &#x60;05&#x60;, &#x60;06&#x60;, and
   * &#x60;07&#x60;. Use &#x60;07&#x60; when no other value applies and provide details in
   * &#x60;notes&#x60;. Maximum length: 32 characters.
   */
  private String shippingMethodIndicator;
}
