/*
 * v1_billing_invoice_update
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** InvoiceShipping */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InvoiceShipping {

  private UserName shippingName;

  private Address shippingAddress;

  /** The shipping carrier. Maximum length: 128 characters. */
  private String shippingCarrier;

  /** The shipping number. Maximum length: 128 characters. */
  private String shippingNumber;

  /** The shipping phone no. Maximum length: 16 characters. */
  private String shippingPhoneNo;

  /** The ship to email. Maximum length: 256 characters. */
  private String shipToEmail;

  /** The notes. Maximum length: 512 characters. */
  private String notes;

  /** The shipping fee id. Maximum length: 64 characters. */
  private String shippingFeeId;

  private Amount shippingFee;

  /** The shipping description. Maximum length: 256 characters. */
  private String shippingDescription;

  private DeliveryEstimate deliveryEstimate;

  /** The tracking url. Maximum length: 2048 characters. */
  private String trackingUrl;

  /** The shipping method indicator. Maximum length: 32 characters. */
  private String shippingMethodIndicator;
}
