/*
 * v1_billing_receipt_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Item */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Item {

  /** The item id. Maximum length: 64 characters. */
  private String itemId;

  /** The description. Maximum length: 512 characters. */
  private String description;

  /** The quantity. */
  private Integer quantity;

  private Amount unitAmount;

  private Amount amount;

  private Amount usageAmount;

  /** The usage quantity. */
  private String usageQuantity;

  /** The usage unit. Maximum length: 32 characters. */
  private String usageUnit;

  private Amount discountAmount;

  private Amount taxAmount;

  /** The period start. Maximum length: 24 characters. */
  private String periodStart;

  /** The period end. Maximum length: 24 characters. */
  private String periodEnd;

  /** The proration. */
  private Boolean proration;

  /** The creation time. Maximum length: 24 characters. */
  private String gmtCreate;

  /** The gmt update. Maximum length: 24 characters. */
  private String gmtUpdate;
}
