/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** Lodging */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Lodging {

  /** Hotel name. More information: Maximum length: 128 characters */
  private String hotelName;

  private Address hotelAddress;

  /**
   * Date on which the guest checked in. In the case of a no-show or a reservation, the scheduled
   * arrival date. More information: The value follows the ISO 8601 standard format. For example,
   * \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String checkInDate;

  /**
   * Date on which the guest checked out. More information: The value follows the ISO 8601 standard
   * format. For example, \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String checkOutDate;

  /** Number of rooms booked by the payer. More information: Value range: 1 - unlimited */
  private Integer numberOfNights;

  /** Number of nights booked by the payer. More information: Value range: 1 - unlimited */
  private Integer numberOfRooms;

  /**
   * Name of the guest under which the room is reserved. More information: Maximum size: 100
   * elements
   */
  private List<UserName> guestNames;
}
