/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Logo */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Logo {

  /**
   * The logo name of the card brand. See the Card brands to check the valid values. More
   * information: Maximum length: 12 characters
   */
  private String logoName;

  /** The logo URL of the card brand. More information: Maximum length: 2048 characters */
  private String logoUrl;
}
