/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** Order */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Order {

  /**
   * The unique ID to identify the order on the merchant side, which is assigned by the merchant
   * that provides services or goods directly to the customer. This field is used for user
   * consumption records display and other further actions such as disputes track or handling of
   * customer complaints. More information: Maximum length: 64 characters
   */
  private String referenceOrderId;

  /**
   * Summary description of the order, which is used for user consumption records display or other
   * further actions. More information: Maximum length: 256 characters
   */
  private String orderDescription;

  private Amount orderAmount;

  private Merchant merchant;

  /**
   * Goods information, including the ID, name, price, and quantity of the goods in the order. Note:
   * Specify this parameter if you require risk control. Providing this information helps to
   * increase the accuracy of anti-money laundering and fraud detection, and increase payment
   * success rates. More information: Maximum size: 100 elements
   */
  private List<Goods> goods;

  private Shipping shipping;

  private Buyer buyer;

  private Env env;

  /**
   * Extended information data, including information for special use cases. Note: Specify this
   * field when you need to use the extended information.
   */
  private String extendInfo;

  private Transit transit;

  private Lodging lodging;

  private Gaming gaming;

  private Boolean needDeclaration;

  private String orderTest;

  private Declaration declaration;

  /** test */
  private String orderType;
}
