/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** OrderCodeForm */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderCodeForm {

  private String paymentMethodType;

  /**
   * Expiry time of the order code information. More information: The value follows the ISO 8601
   * standard format. For example, \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String expireTime;

  /** Details about the code. More information: Maximum size: 4 elements */
  private List<CodeDetail> codeDetails;

  /**
   * Extended information. Note: This field is returned when extended information exists. More
   * information: Maximum length: 2048 characters
   */
  private String extendInfo;
}
