/*
 * subscriptions_update
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** OrderInfo */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderInfo {

  private Amount orderAmount;
}
