/*
 * v1_tax_inquireTransactionList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Paginator */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Paginator {

  /** The current page number, starting from 1. */
  private Integer currentPage;

  /** The number of records returned per page. */
  private Integer pageSize;

  /** The total number of pages. */
  private Integer totalPage;

  /** The total number of records that match the query criteria. */
  private Integer totalCount;
}
