/*
 * v1_tax_inquireTransactionList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Paginator */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Paginator {

  /**
   * The current page number, starting from 1. If currentPage exceeds totalPage, transactions is
   * returned as an empty array.
   */
  private Integer currentPage;

  /**
   * The number of records returned per page. The value must be a positive integer; otherwise,
   * PARAM_ILLEGAL is returned.
   */
  private Integer pageSize;

  /** The total number of pages in the query result. */
  private Integer totalPage;

  /** The total number of tax transactions that match the query criteria. */
  private Integer totalCount;
}
