package com.alipay.global.api.model.ams;

public enum PassengerIdType {
    PASSPORT, NATIONAL_ID_CARD, DRIVER_LICENSE, MILITARY_ID, GREEN_CARD, TRAVEL_DOCUMENT, ALIEN_REGISTRATION_CARD, BIRTH_CERTIFICATE, OTHERS
}
