/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/** Type of passenger identification */
public enum PassengerIdType {
  PASSPORT("PASSPORT"),

  NATIONAL_ID_CARD("NATIONAL_ID_CARD"),

  DRIVER_LICENSE("DRIVER_LICENSE"),

  MILITARY_ID("MILITARY_ID"),

  GREEN_CARD("GREEN_CARD"),

  TRAVEL_DOCUMENT("TRAVEL_DOCUMENT"),

  ALIEN_REGISTRATION_CARD("ALIEN_REGISTRATION_CARD"),

  BIRTH_CERTIFICATE("BIRTH_CERTIFICATE"),

  OTHERS("OTHERS");

  private String value;

  PassengerIdType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static PassengerIdType fromValue(String value) {
    for (PassengerIdType b : PassengerIdType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
