/*
 * vaults_inquireVaulting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** PaymentMethodDetail */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentMethodDetail {

  private PaymentMethodDetailType paymentMethodDetailType;

  private CardPaymentMethodDetail card;

  private ExternalPaymentMethodDetail externalAccount;

  private DiscountPaymentMethodDetail discount;

  private CouponPaymentMethodDetail coupon;

  /**
   * The type of payment method to be vaulted. The value of this parameter is fixed to CARD. More
   * information: Maximum length: 64 characters
   */
  private String paymentMethodType;

  private String extendInfo;

  private Wallet wallet;

  private String interactionType;
}
