/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** PaymentMethodTypeItem */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentMethodTypeItem {

  /**
   * The payment method type that is included in payment method options. See Payment methods to
   * check the valid values. More information: Value range: 64
   */
  private String paymentMethodType;

  /**
   * The priority order of the payment methods configured by the user is indicated by numerical
   * values, with smaller numbers representing higher priority. If the user does not specify a
   * setting, Antom will apply a default sorting method. More information: Value range: [1, +∞)
   */
  private String paymentMethodOrder;

  /**
   * Indicates whether the payment method selected by the user is displayed as a quick payment
   * method. The currently supported quick payment methods include ALIPAY_CN, APPLEPAY, and
   * GOOGLAPAY. The valid values include: true: The payment method selected by the user is displayed
   * as a quick payment method. false: The payment method selected by the user is not displayed as a
   * quick payment method.
   */
  private String expressCheckout;
}
