/*
 * /ams/v1/subscriptions/inquireSubscriptionPayment
 * Use this API to retrieve a list of payments for a subscription. After the API is called successfully, you can obtain the subscription's transaction information, such as transaction time, phase number, payment method, amount, and disputes.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/**
 * Indicates the payment status. Valid values are: - SUCCESS: Indicates that the payment succeeds. -
 * FAIL: Indicates that the payment fails.
 */
public enum PaymentStatus {
  SUCCESS("SUCCESS"),

  FAIL("FAIL");

  private String value;

  PaymentStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static PaymentStatus fromValue(String value) {
    for (PaymentStatus b : PaymentStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
