/*
 * payments_pay
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** PaymentMethodPaymentMethodMetaDataChannelOptionBill */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentMethodPaymentMethodMetaDataChannelOptionBill {

  /**
   * The promotion code(s) agreed between the merchant and Sequra, identifying promotional
   * activities such as interest-free installments. When multiple codes exist, concatenate with
   * commas (max 99 codes, each max 20 characters). IPay only passes through and does not validate.
   * Required when the merchant has agreed promotion codes with Sequra. Default: not transmitted, no
   * impact. Nullable: yes.
   */
  private String channelPromotionCode;
}
