/*
 * subscriptions_update
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** PeriodRule */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PeriodRule {

  /**
   * The subscription period type. Valid values are: YEAR: indicates that the subscription period is
   * measured in years. MONTH: indicates that the subscription period is measured in months. WEEK:
   * indicates that the subscription period is measured in weeks. DAY: indicates that the
   * subscription period is measured in days. More information: Maximum length: 20 characters
   */
  private String periodType;

  /**
   * The number of period types within one subscription period. For example, if the value of
   * periodType is MONTH and the value of periodCount is 2, it means that the subscription period is
   * two months. More information: Value range: [1, +∞)
   */
  private Integer periodCount;
}
