/*
 * /ams/v1/subscriptions/inquiry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/** PeriodRule */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PeriodRule {

  /**
   * The subscription period type. Valid values are: WEEK: indicates that the subscription period is
   * measured in weeks. MONTH: indicates that the subscription period is measured in months.
   * QUARTER: indicates that the subscription period is measured in quarters. HALF_YEAR: indicates
   * that the subscription period is measured in half years. YEAR: indicates that the subscription
   * period is measured in years. More information: Maximum length: 20 characters
   */
  public enum PeriodTypeEnum {
    WEEK("WEEK"),

    MONTH("MONTH"),

    QUARTER("QUARTER"),

    HALF_YEAR("HALF_YEAR"),

    YEAR("YEAR");

    private String value;

    PeriodTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PeriodTypeEnum fromValue(String value) {
      for (PeriodTypeEnum b : PeriodTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  /**
   * The subscription period type. Valid values are: WEEK: indicates that the subscription period is
   * measured in weeks. MONTH: indicates that the subscription period is measured in months.
   * QUARTER: indicates that the subscription period is measured in quarters. HALF_YEAR: indicates
   * that the subscription period is measured in half years. YEAR: indicates that the subscription
   * period is measured in years. More information: Maximum length: 20 characters
   */
  private PeriodTypeEnum periodType;

  /** Number of periods */
  private Integer period;

  private Amount price;

  /**
   * The number of period types within one subscription period. For example, if the value of
   * periodType is MONTH and the value of periodCount is 2, it means that the subscription period is
   * two months. More information: Value range: 1 - unlimited
   */
  private Integer periodCount;
}
