/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Plan */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Plan {

  /**
   * The interest rate the customer is charged on the installments. More information: Maximum
   * length: 8 characters
   */
  private String interestRate;

  private Amount minInstallmentAmount;

  private Amount maxInstallmentAmount;

  /**
   * The number of installment payments. The valid value is from 2 to 12. More information: Maximum
   * length: 8 characters
   */
  private String installmentNum;

  /**
   * The interval of each installment payment. The valid value is MONTH. More information: Maximum
   * length: 16 characters
   */
  private String interval;

  /** Indicates whether the installment payment is available. */
  private Boolean enabled;

  /**
   * Extended information field, used to return extended information of the payment installment plan
   * in the payment consultation interface. The extended fields in the installment plan include
   * interest rates and various amount details to meet the merchant&#39;s amount display
   * requirements. More information: Maximum length: 4096 characters
   */
  private String extendInfo;
}
