/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/** Gets or Sets ProductCodeType */
public enum ProductCodeType {
  CASHIER_PAYMENT("CASHIER_PAYMENT"),

  AGREEMENT_PAYMENT("AGREEMENT_PAYMENT"),

  IN_STORE_PAYMENT("IN_STORE_PAYMENT");

  private String value;

  ProductCodeType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ProductCodeType fromValue(String value) {
    for (ProductCodeType b : ProductCodeType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
