/*
 * v1_billing_product_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** Product */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Product {

  /** System-generated product ID */
  private String productId;

  /**
   * The idempotency key supplied when the product was created. Returned only when result.resultCode
   * is SUCCESS.
   */
  private String productRequestId;

  /** Product name */
  private String name;

  /**
   * Filter by product type. O - When provided, returns only products of the specified type; when
   * absent, returns all types. Enum: SERVICE, GOOD. Can be null; default null. Invalid values
   * return PARAM_ILLEGAL error
   */
  private String type;

  /** Product description. O - May be null in the response when the value is not set */
  private String description;

  /** Product image URLs */
  private List<String> images;

  /** Product-level unit label. O - May be null in the response when the value is not set */
  private String unitLabel;

  /**
   * Custom key-value metadata stored as JSON string The value must be a valid JSON object string.
   */
  private String metadata;

  /**
   * Filter by active status. O - true&#x3D;return only active products, false&#x3D;return only
   * deactivated products, absent or null&#x3D;return all products. No default value
   */
  private Boolean active;

  /** ISO 8601 creation timestamp */
  private String createdAt;

  /**
   * ISO 8601 deactivation timestamp. O - Returned when product has been deactivated
   * (active&#x3D;false); absent when product is active
   */
  private String deactivatedAt;

  /**
   * ISO 8601 last update timestamp. O - Returned when non-null; absent from response if never
   * updated after creation
   */
  private String updatedAt;
}
