/*
 * v1_billing_promotionCode_create
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** PromotionCodeCreateMinAmount */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PromotionCodeCreateMinAmount {

  /**
   * Amount value in the smallest currency unit (minor units, e.g. cents). No leading zeros. Cannot
   * be empty.
   */
  private String value;

  /** ISO 4217 alpha-3 currency code. */
  private String currency;
}
