/*
 * v1_billing_coupon_create
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** PromotionCode */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PromotionCode {

  /**
   * Idempotency key for the nested promotion code. Must be unique per merchant. Independent of the
   * coupon&#39;s &#x60;couponRequestId&#x60;.
   */
  private String promotionCodeRequestId;

  /**
   * Public promotion code string. If not provided, the server auto-generates a 12-character
   * readable code (uppercase letters + digits, ambiguous chars O/0/I/1/L removed). Must be unique
   * per merchant.
   */
  private String code;

  /** UTC timestamp (ISO 8601) after which the code expires. */
  private String expiryTime;

  private Amount minAmount;

  /**
   * If &#x60;true&#x60;, each customer can only redeem this code once. Default: &#x60;false&#x60;.
   */
  private Boolean oneTimeOnly;

  /**
   * If set, restricts this code to a specific customer. Must be a valid customerId in the system.
   */
  private String customerId;

  /**
   * Merchant-defined key-value pairs stored as JSON string. Enforced constraints: max 50 keys; each
   * key max 40 characters; each value max 500 characters. Requests exceeding these limits return
   * &#x60;PARAM_ILLEGAL&#x60;. The value must be a valid JSON object string.
   */
  private String metadata;

  /** Maximum redemption count for this code. If not set or 0, unlimited. Value range: 0-999999. */
  private Integer maxRedemptions;
}
