/*
 * v1_billing_promotionCode_create
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** PromotionCodeCreateMinAmount */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PromotionCodeCreateMinAmount {

  /**
   * The value of the amount as a positive integer in the smallest currency unit. Maximum length: 16
   * characters.
   */
  private String value;

  /**
   * The 3-letter currency code that follows the ISO 4217 standard. Maximum length: 3 characters.
   */
  private String currency;
}
