/*
 * v1_billing_receipt_inquireDetails
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** ReceiptItem */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReceiptItem {

  /** Line item ID. Unique identifier. */
  private String itemId;

  /** Line item description (e.g., \&quot;1 x Pro Plan (at $10.00/month)\&quot;). */
  private String description;

  /** Quantity of the item. Default: 1. */
  private Integer quantity;

  private Amount unitAmount;

  private Amount amount;

  private Amount usageAmount;

  /** Metered usage quantity. Null if not metered. */
  private String usageQuantity;

  /** Usage unit (e.g., &#x60;requests&#x60;, &#x60;gb&#x60;). Null if not metered. */
  private String usageUnit;

  private Amount discountAmount;

  private Amount taxAmount;

  /** ISO 8601 timestamp of coverage period start. Null if not subscription-based. */
  private String periodStart;

  /** ISO 8601 timestamp of coverage period end. Null if not subscription-based. */
  private String periodEnd;

  /** Whether this is a proration adjustment. Default: false. */
  private Boolean proration;

  /** ISO 8601 timestamp of line item creation. Maximum length: 29 characters. */
  private String gmtCreate;

  /** ISO 8601 timestamp of last line item update. Maximum length: 29 characters. */
  private String gmtUpdate;
}
