/*
 * baa-inquiryStatement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** ResultResult */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ResultResult {

  /** The result code. */
  private String resultCode;

  private ResultStatusType resultStatus;

  /** The result message. */
  private String resultMessage;
}
