/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** RiskThreeDSResult */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RiskThreeDSResult {

  /** The version of 3D Secure protocol */
  private String threeDSVersion;

  /** Indicates the type of user interactions during 3DS 2.0 authentication */
  private String threeDSInteractionMode;

  /** Electronic Commerce Indicator (ECI) that is returned by the card scheme */
  private String eci;

  /** The cardholder authentication value */
  private String cavv;
}
