/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** RiskOrder */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RiskOrder {

  /** The order type */
  private String orderType;

  /** The webpage where the buyer accessed the merchant. */
  private String referringSite;
}
