/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** RiskBuyer */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RiskBuyer {

  /** The buyer&#39;s note to a merchant. */
  private String noteToMerchant;

  /** The buyer&#39;s note to a deliveryman or a take-out rider. */
  private String noteToShipping;

  /** The successful orders the buyer made within the last one hour. */
  private Integer orderCountIn1H;

  /** The successful orders the buyer made within the last 24 hour. */
  private Integer orderCountIn24H;
}
