/*
 * authorizations_consult
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/** Gets or Sets ScopeType */
public enum ScopeType {
  BASE_USER_INFO("BASE_USER_INFO"),

  AGREEMENT_PAY("AGREEMENT_PAY"),

  USER_INFO("USER_INFO"),

  USER_LOGIN_ID("USER_LOGIN_ID"),

  HASH_LOGIN_ID("HASH_LOGIN_ID"),

  SEND_OTP("SEND_OTP"),

  TAOBAO_REBIND("TAOBAO_REBIND");

  private String value;

  ScopeType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ScopeType fromValue(String value) {
    for (ScopeType b : ScopeType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
