/*
 * payments_refund
 *       Use this API to initiate a refund against a successful payment. The refund can be full or partial.        A transaction can have multiple refunds as long as the total refund amount is less than or equal to the original transaction amount.         If the refund request is out of the refund window determined in the contract, the refund request will be declined.    Note: Use the same refundRequestId field to retry a refund in case of timeout or when the returned resultStatus is ​U​. The refundRequestId field is designed to be idempotent.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** SplitDetail */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SplitDetail {

  /**
   * The original split recipient from which the funds are reversed for this refund. Valid values
   * are: SELLER: indicates that the payment funds were split to the seller. MARKETPLACE: indicates
   * that the payment funds were split to the marketplace. PLATFORM: indicates that the payment
   * funds were split to the platform. ISV: indicates that the payment funds were split to the
   * independent software vendor. Note: The value must exist in the successful split of the original
   * payment or capture. Unknown values are rejected with the existing PARAM_ILLEGAL behavior. More
   * information: Maximum length: 32 characters
   */
  private String splitTo;

  private Amount splitAmount;

  private Amount actualSplitAmount;

  /**
   * The merchant-supplied remark for billing and reconciliation. If this field is provided, it is
   * reflected in the bill and returned with the corresponding refund split detail. Omission does
   * not affect refund or split-reversal processing. More information: Maximum length: 256
   * characters
   */
  private String description;
}
