/*
 * marketplace_register
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** StockInfo */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StockInfo {

  /**
   * The region or country where the company is listed. More information: Maximum length: 2
   * characters
   */
  private String listedRegion;

  /**
   * The ticker symbol of the stock. Specify this parameter when the value of
   * merchantInfo.company.registeredAddress.region is US. More information: Maximum length: 32
   * characters
   */
  private String tickerSymbol;
}
