/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/**
 * The subscription status. Valid values are: - ACTIVE: indicates that the subscription is active. -
 * CANCELLED: indicates that the subscription is cancelled. - TERMINATED: indicates that the
 * subscription is terminated.
 */
public enum SubscriptionStatus {
  ACTIVE("ACTIVE"),

  CANCELLED("CANCELLED"),

  TERMINATED("TERMINATED");

  private String value;

  SubscriptionStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SubscriptionStatus fromValue(String value) {
    for (SubscriptionStatus b : SubscriptionStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
