/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** SubscriptionInfo */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SubscriptionInfo {

  /** Description of the subscription plan */
  private String subscriptionDescription;

  /** Start time of the subscription in ISO 8601 format */
  private String subscriptionStartTime;

  /** End time of the subscription in ISO 8601 format */
  private String subscriptionEndTime;

  private PeriodRule periodRule;

  /** List of trial periods for the subscription */
  private List<Trial> trials;

  /** URL for subscription notifications */
  private String subscriptionNotifyUrl;

  /** Expiry time of the subscription in ISO 8601 format */
  private String subscriptionExpiryTime;

  /**
   * Field is used only in the PIX recurrence scenario. Whether to allow a retry in the event that a
   * recurring payment fails due to insufficient balance.
   */
  private Boolean allowRetry;

  private Amount maxAmountFloor;
}
