/*
 * v1_billing_subscription_inquireList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Subscription */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Subscription {

  /** The subscription ID. Maximum length: 64 characters. */
  private String subscriptionId;

  /** The current status. Maximum length: 20 characters. */
  private String status;

  /** The unique ID assigned by Antom to identify a customer. Maximum length: 64 characters. */
  private String customerId;

  /** The current period end. */
  private String currentPeriodEnd;

  /** The created at. */
  private String createdAt;
}
