/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** SupportBank */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SupportBank {

  /** The unique code of the bank. See the Bank list to check the valid values. */
  private String bankIdentifierCode;

  /**
   * The short name of the bank. The unique code of the bank. See the Bank list to check the valid
   * values.
   */
  private String bankShortName;

  private Logo bankLogo;
}
