/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** SupportCardBrand */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SupportCardBrand {

  /**
   * The name of the card brand. Valid values are: VISA: indicates Visa. MASTERCARD: indicates
   * Mastercard. AMEX: indicates American Express (Amex). HIPERCARD: indicates Hipercard. ELO:
   * indicates Elo.
   */
  private String cardBrand;

  private Logo logo;
}
