/*
 * v1_tax_updateSettings
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** TaxAddress */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TaxAddress {

  /** The country or region code. Maximum length: 2 characters. */
  private String country;

  /** The region. Maximum length: 10 characters. */
  private String region;

  /** The county. Maximum length: 64 characters. */
  private String county;

  /** The city. Maximum length: 64 characters. */
  private String city;

  /** The district. Maximum length: 64 characters. */
  private String district;

  /** The line 1. Maximum length: 256 characters. */
  private String line1;

  /** The line 2. Maximum length: 256 characters. */
  private String line2;

  /** The postal code. Maximum length: 16 characters. */
  private String postalCode;
}
