/*
 * v1_tax_inquireCalculation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** TaxCalculatedLineItem */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TaxCalculatedLineItem {

  /** The goods reference ID. Maximum length: 128 characters. */
  private String goodsReferenceId;

  /** The amount. Maximum length: 19 characters. */
  private String amount;

  /** The quantity. */
  private Integer quantity;

  /** The tax code. Maximum length: 32 characters. */
  private String taxCode;

  /** The tax behavior. Maximum length: 16 characters. */
  private String taxBehavior;

  /** The tax amount. Maximum length: 19 characters. */
  private String taxAmount;

  /** The tax breakdown. */
  private List<TaxBreakdown> taxBreakdown;
}
