/*
 * v1_tax_inquireCalculation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** TaxCalculatedExemption */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TaxCalculatedExemption {

  /** The tax exemption certificate number. Maximum length: 64 characters. */
  private String certificateNumber;

  /** The tax exemption type. Maximum length: 32 characters. */
  private String exemptionType;

  private TaxCalculatedExemptionJurisdiction jurisdiction;

  /**
   * The ISO 8601 time with a timezone when the tax exemption becomes effective. Maximum length: 32
   * characters.
   */
  private String effectiveFrom;
}
