/*
 * v1_tax_calculate
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** TaxId */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TaxId {

  /**
   * The value of the amount as a positive integer in the smallest currency unit. Maximum length: 64
   * characters.
   */
  private String value;

  /** The country or region code. Maximum length: 2 characters. */
  private String country;

  /** The region. Maximum length: 10 characters. Note: See documentation for details. */
  private String region;

  /** The customer name recorded for tax purposes. Maximum length: 128 characters. */
  private String name;
}
