/*
 * payments_ inquiryPayment
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** ThreeDSResult */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ThreeDSResult {

  /** The version of 3D Secure protocol */
  private String threeDSVersion;

  /** Electronic Commerce Indicator (ECI) that is returned by the card scheme */
  private String eci;

  /** The cardholder authentication value */
  private String cavv;

  /** dsTransactionId */
  private String dsTransactionId;

  /**
   * The unique transaction identifier assigned by the Directory Server (DS) for 3D Secure
   * authentication
   */
  private String xid;
}
