/*
 * marketplace_createTransfer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** TransferToDetail */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TransferToDetail {

  private PaymentMethod transferToMethod;

  /**
   * A 3-character ISO-4217 currency code representing the currency that the beneficiary collects.
   * More information: Maximum length: 3 characters
   */
  private String transferToCurrency;

  private Amount feeAmount;

  private Amount actualTransferToAmount;

  /**
   * Defines the purpose of the transfer. The value of this parameter is fixed to GSD, which means
   * goods bought or sold. More information: Maximum length: 3 characters
   */
  private String purposeCode;

  /**
   * If you specify this parameter, Antom will send the transfer result notification to this URL.
   * The URL must be either specified in the request or set in Antom Dashboard. Specify this
   * parameter if you want to receive an asynchronous notification of the transfer result. If this
   * URL is specified in both the request and Antom Dashboard, the value specified in the request
   * takes precedence. More information: Maximum length: 2048 characters
   */
  private String transferNotifyUrl;

  /**
   * Remark information for the transfer. Specify this parameter if you want to provide additional
   * remarks or relevant information regarding the payout. More information: Maximum length: 1024
   * characters
   */
  private String transferRemark;
}
