/*
 * payments_ inquiryPayment
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/** Gets or Sets TransactionStatusType */
public enum TransactionStatusType {
  SUCCESS("SUCCESS"),

  FAIL("FAIL"),

  PROCESSING("PROCESSING"),

  CANCELLED("CANCELLED"),

  PENDING("PENDING");

  private String value;

  TransactionStatusType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TransactionStatusType fromValue(String value) {
    for (TransactionStatusType b : TransactionStatusType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
