/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** Transit */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Transit {

  private TransitType transitType;

  /**
   * Information about sections of the trip, including departure time, arrival time, departure
   * address, arrival address, transportation company name, carrier code and service type. More
   * information: Maximum size: 10 elements
   */
  private List<Leg> legs;

  /**
   * Information about the passenger of the trip, including the passenger names, passenger email and
   * phone number. More information: Maximum size: 100 elements
   */
  private List<Passenger> passengers;
}
