/*
 * /ams/v1/subscriptions/inquireSubscription
 * Use this API to retrieve a subscription using its ID returned by Antom after successfully created. After this API is called successfully, you can obtain detailed information about that subscription, including its status, period, amount, etc.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.List;
import lombok.*;

/** TrialPlan */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TrialPlan {

  /** Indicates the last date of trial phases. */
  private String trialEndTime;

  /** Total free trial days. */
  private Integer freeTrialDays;

  /** Subscription periods that apply trial plan. */
  private List<TrialPhase> phases;
}
