/*
 * payments_createPaymentSession
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** TrialPhase */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TrialPhase {

  /** The subscription period that applies trial. */
  private Integer phaseNo;

  private Amount trialAmount;
}
