package com.alipay.global.api.request.ams.notify;

import com.alipay.global.api.model.ams.CreditNoteInfo;
import com.alipay.global.api.model.ams.NotifyInvoiceInfo;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class AlipayCreditNoteNotify extends AlipayNotify {

  /** The unique notification ID generated by Antom for each delivery. Same notifyId is reused for retries. Maximum length: 64 characters. */
  private String notifyId;

  /** The merchant-assigned idempotency key from credit note creation. Same across all lifecycle events for the same credit note. Maximum length: 64 characters. */
  private String creditNoteRequestId;

  /** The lifecycle event type. Valid values: CREATED, VOIDED, REFUND_SUCCEEDED, REFUND_FAILED. Maximum length: 32 characters. */
  private String creditNoteNotificationType;

  /** The customer ID associated with this credit note. Maximum length: 64 characters. */
  private String customerId;

  /** The full credit note object containing status, amounts, refund details, reason, and line items. */
  private CreditNoteInfo creditNote;

  /** The associated invoice summary providing context and full amount breakdown. */
  private NotifyInvoiceInfo invoice;
}
