package com.alipay.global.api.request.ams.notify;


public class AlipayAuthNotify extends AlipayNotify{

    /**
     * Authorization notification type
     */
    private String authorizationNotifyType;

    /**
     * authClientId
     */
    private String authClientId;

    /**
     * The access token that is used to access the corresponding scope of the user resource
     */
    private String accessToken;

    /**
     * A string that is generated by the acquirer to represent the consult request
     */
    private String authState;

    /**
     * The authorization code, used for getting an access token
     */
    private String authCode;

    /**
     * The reason why the authorization is canceled
     */
    private String reason;

    /**
     * The login ID that the user used to register in the wallet
     */
    private String userLoginId;

    /**
     * The ID assigned by the payment method provider to identify a user
     */
    private String userId;

    public String getAuthorizationNotifyType() {
        return authorizationNotifyType;
    }

    public void setAuthorizationNotifyType(String authorizationNotifyType) {
        this.authorizationNotifyType = authorizationNotifyType;
    }

    public String getAuthClientId() {
        return authClientId;
    }

    public void setAuthClientId(String authClientId) {
        this.authClientId = authClientId;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getAuthState() {
        return authState;
    }

    public void setAuthState(String authState) {
        this.authState = authState;
    }

    public String getAuthCode() {
        return authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getUserLoginId() {
        return userLoginId;
    }

    public void setUserLoginId(String userLoginId) {
        this.userLoginId = userLoginId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}
