package com.alipay.global.api.request.ams.notify;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class AlipayAuthNotify extends AlipayNotify {

  /** Authorization notification type */
  private String authorizationNotifyType;

  /** authClientId */
  private String authClientId;

  /** The access token that is used to access the corresponding scope of the user resource */
  private String accessToken;

  /** A string that is generated by the acquirer to represent the consult request */
  private String authState;

  /** The authorization code, used for getting an access token */
  private String authCode;

  /** The reason why the authorization is canceled */
  private String reason;

  /** The login ID that the user used to register in the wallet */
  private String userLoginId;

  /** The ID assigned by the payment method provider to identify a user */
  private String userId;
}
