/*
 * v1_payments_reserve_updateHold
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.pay;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayUpdateHoldResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayUpdateHoldResponse extends AlipayResponse {

  /** The updated manual hold identifier. Returned when result.resultStatus is S. */
  private String holdId;

  /**
   * The persisted automatic release time in UTC ISO 8601 format. Returned when result.resultStatus
   * is S.
   */
  private String releaseTime;
}
