/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.pay;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.AcquirerInfo;
import com.alipay.global.api.model.ams.Amount;
import com.alipay.global.api.model.ams.ChallengeActionForm;
import com.alipay.global.api.model.ams.OrderCodeForm;
import com.alipay.global.api.model.ams.PspCustomerInfo;
import com.alipay.global.api.model.ams.Quote;
import com.alipay.global.api.model.ams.RedirectActionForm;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayPayResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayPayResponse extends AlipayResponse {

  /**
   * The unique ID that is assigned by a merchant to identify a payment request. Note: This field is
   * returned when resultCode is PAYMENT_IN_PROCESS. More information: Maximum length: 64 characters
   */
  private String paymentRequestId;

  /**
   * The unique ID that is assigned by Antom to identify a payment. Note: This field is returned
   * when resultCode is PAYMENT_IN_PROCESS. More information: Maximum length: 64 characters
   */
  private String paymentId;

  private Amount paymentAmount;

  /**
   * Used by the Antom client SDK to render the checkout page. This parameter is returned if the
   * merchant app has integrated Antom client SDK. After receiving the parameter, you can call the
   * showPaymentSheet API of the Antom client SDK. More information: Maximum length: 20000
   * characters
   */
  private String paymentData;

  private Amount actualPaymentAmount;

  private Quote paymentQuote;

  private String paymentTime;

  /**
   * The date and time when the payment is created. Note: This field is returned when resultCode is
   * PAYMENT_IN_PROCESS. More information: The value follows the ISO 8601 standard format. For
   * example, \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String paymentCreateTime;

  private String authExpiryTime;

  private Amount nonGuaranteeCouponValue;

  private String paymentActionForm;

  private PspCustomerInfo pspCustomerInfo;

  private ChallengeActionForm challengeActionForm;

  private RedirectActionForm redirectActionForm;

  private OrderCodeForm orderCodeForm;

  private Amount grossSettlementAmount;

  private Quote settlementQuote;

  private String extendInfo;

  /**
   * The URL that redirects users to a WAP or WEB page in the default browser or the embedded
   * WebView. Note: When the value of resultCode is ​PAYMENT_IN_PROCESS​, at least one of schemeUrl,
   * applinkUrl, and normalUrl is to be returned. More information: Maximum length: 2048 characters
   */
  private String normalUrl;

  /**
   * The URL scheme that redirects users to open an app in an Android or iOS system when the target
   * app is installed. Note: When the value of resultCode is ​PAYMENT_IN_PROCESS​, at least one of
   * schemeUrl, applinkUrl, and normalUrl is to be returned. More information: Maximum length: 2048
   * characters
   */
  private String schemeUrl;

  /**
   * The URL that redirects users to open an app when the target app is installed, or to open a WAP
   * page when the target app is not installed. For Android, the URL is a Native App Link. For iOS,
   * the URL is a Universal Link. Note: When the value of resultCode is ​PAYMENT_IN_PROCESS​, at
   * least one of schemeUrl, applinkUrl, and normalUrl is to be returned. More information: Maximum
   * length: 2048 characters
   */
  private String applinkUrl;

  /**
   * Android package name, which is used by Android apps to open a cashier page. Note: This field is
   * returned when resultCode is ​PAYMENT_IN_PROCESS​ and terminalType is APP or WAP.
   */
  private String appIdentifier;

  private PaymentResultInfo paymentResultInfo;

  private AcquirerInfo acquirerInfo;

  /** Promotion result. */
  private List<PromotionResult> promotionResult;
}
