/*
 * vaults_inquireVaulting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.pay;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.PaymentMethodDetail;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayVaultingQueryResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayVaultingQueryResponse extends AlipayResponse {

  /**
   * The unique ID that is assigned by a merchant to identify a card vaulting request. More
   * information: Maximum length: 64 characters
   */
  private String vaultingRequestId;

  /**
   * The URL that redirects users to a WAP or WEB page in the default browser or the embedded
   * WebView. Note: When the value of result.resultStatus is S and the value of vaultingStatus is
   * PROCESSING, one or more of the following URLs may be returned: schemeUrl, applinkUrl, and
   * normalUrl. When the value of paymentMethodType is CARD, the user is required to complete the
   * 3DS authentication on the page accessed through this URL. More information: Maximum length:
   * 2048 characters
   */
  private String normalUrl;

  /**
   * The URL scheme that redirects users to open an App in an Android or iOS system when the target
   * App is installed. Note: When the value of result.resultStatus is S and the value of
   * vaultingStatus is PROCESSING, one or more of the following URLs may be returned: schemeUrl,
   * applinkUrl, and normalUrl. More information: Maximum length: 2048 characters
   */
  private String schemeUrl;

  /**
   * The URL that redirects users to open an app when the target app is installed, or to open a WAP
   * page when the target app is not installed. For Android, the URL is a Native App Link. For iOS,
   * the URL is a Universal Link. Note: When the value of result.resultStatus is S and the value of
   * vaultingStatus is PROCESSING, one or more of the following URLs may be returned: schemeUrl,
   * applinkUrl, and normalUrl. More information: Maximum length: 2048 characters
   */
  private String applinkUrl;

  /**
   * Indicates the payment method&#39;s vaulting status. Valid values are: SUCCESS: indicates that
   * the vaulting is successful. FAIL: indicates that the vaulting failed. PROCESSING: indicates
   * that the vaulting is under process. This parameter is returned when the value of
   * result.resultStatus is S. More information: Maximum length: 10 characters
   */
  private String vaultingStatus;

  private PaymentMethodDetail paymentMethodDetail;

  /** Metadata for custom data transmission */
  private String metadata;

  /**
   * The vaulting result code, corresponding to vaultingStatus. When vaultingStatus is SUCCESS, the
   * value is SUCCESS. When vaultingStatus is PROCESSING, the value is VERIFICATION_IN_PROCESS. When
   * vaultingStatus is FAIL, the value is a specific error code returned by the card scheme, issuing
   * bank, or acquirer; when the channel error cannot be mapped, the value is PROCESS_FAIL. Note:
   * This parameter is returned when the value of result.resultStatus is S. Possible values when
   * vaultingStatus is FAIL include: ACCESS_DENIED, ACCOUNT_CLOSED, AUTHENTICATION_REQUIRED,
   * BLOCKED_FIRST_USED, CARD_EXPIRED, CARD_NOT_SUPPORTED, DO_NOT_HONOR, FRAUD_REJECT,
   * INVALID_CARD_NUMBER, INVALID_CVV, INVALID_EXPIRATION_DATE, LOST_CARD, NO_SELECTED_ACCOUNT,
   * ORDER_IS_CLOSED, PAYMENT_AMOUNT_EXCEED_LIMIT, PAYMENT_COUNT_EXCEED_LIMIT, PICKUP_CARD, POLICY,
   * PROCESS_FAIL, RESTRICTED_CARD, STOLEN_CARD, USER_BALANCE_NOT_ENOUGH,
   * USER_PAYMENT_VERIFICATION_FAILED, VERIFY_TIMES_EXCEED_LIMIT. Additional values may be added in
   * the future as channel capabilities evolve. More information: Maximum length: 64 characters
   */
  private String vaultingResultCode;

  /**
   * The readable description of vaultingResultCode. When vaultingResultCode is SUCCESS, the value
   * is \&quot;success.\&quot;. When vaultingResultCode is VERIFICATION_IN_PROCESS, the value is
   * \&quot;The verification is still under process.\&quot;. When vaultingStatus is FAIL, the value
   * is the specific error description corresponding to vaultingResultCode. Note: This parameter is
   * returned when the value of result.resultStatus is S. More information: Maximum length: 256
   * characters
   */
  private String vaultingResultMessage;
}
