/*
 * payments_inquiryRefund
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.pay;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.AcquirerInfo;
import com.alipay.global.api.model.ams.Amount;
import com.alipay.global.api.model.ams.Quote;
import com.alipay.global.api.model.ams.TransactionStatusType;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayInquiryRefundResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInquiryRefundResponse extends AlipayResponse {

  /**
   * The unique ID assigned by Antom to identify a refund. A one-to-one correspondence between
   * refundId and refundRequestId exists. Note: This field is null when the refund record cannot be
   * found, or result.resultStatus is F or U.
   */
  private String refundId;

  /**
   * The unique ID assigned by the merchant to identify a refund request. Note: This field is null
   * when the refund record cannot be found, or result.resultStatus is F or U. More information:
   * Maximum length: 64 characters
   */
  private String refundRequestId;

  private Amount refundAmount;

  private TransactionStatusType refundStatus;

  /**
   * The date and time when the refund reaches a final state of success on the Antom side, not the
   * Alipay+ Mobile Payment Provider (Alipay+ payment methods) side. Note: This field is returned
   * when the value of refundStatus is SUCCESS. More information: The value follows the ISO 8601
   * standard format. For example, \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String refundTime;

  private Amount grossSettlementAmount;

  private Quote settlementQuote;

  private AcquirerInfo acquirerInfo;
}
