/*
 * v1_payments_reserve_createRule
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.pay;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.FundsType;
import com.alipay.global.api.model.ams.PaymentMethodScope;
import com.alipay.global.api.model.ams.ReleaseType;
import com.alipay.global.api.model.ams.RuleStatus;
import com.alipay.global.api.model.ams.TakeType;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayCreateRuleResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCreateRuleResponse extends AlipayResponse {

  /**
   * The Antom-assigned positive numeric reserve rule identifier. Save and return this value
   * unchanged for updates, cancellation, and cursor pagination. Returned only when
   * result.resultCode is SUCCESS.
   */
  private String ruleId;

  /**
   * The ID of the merchant that owns the reserve rule. Returned only when result.resultCode is
   * SUCCESS.
   */
  private String merchantId;

  private FundsType fundsType;

  private TakeType takeType;

  private PaymentMethodScope paymentMethodScope;

  /**
   * The rolling reserve percentage. Returned when takeType is ROLLING and result.resultCode is
   * SUCCESS.
   */
  private Integer ratio;

  private ReleaseType releaseType;

  /**
   * The fixed release instant as an ISO 8601 UTC string, for example 2026-12-31T16:00:00Z. Returned
   * when releaseType is FIXED_TIME and result.resultCode is SUCCESS.
   */
  private String releaseTime;

  /**
   * The rolling retention period in days. Returned when releaseType is INTERVAL_TIME and
   * result.resultCode is SUCCESS.
   */
  private Integer retentionTime;

  private RuleStatus ruleStatus;

  /**
   * The rule creation time as an ISO 8601 UTC string. Returned only when result.resultCode is
   * SUCCESS.
   */
  private String createTime;

  /**
   * The rule last-update time as an ISO 8601 UTC string. Returned only when result.resultCode is
   * SUCCESS.
   */
  private String updateTime;
}
