/*
 * fetchNonce
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.pay;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayVaultsFetchNonceResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayVaultsFetchNonceResponse extends AlipayResponse {

  private String cardToken;
}
