/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.pay;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.PaymentMethodInfo;
import com.alipay.global.api.model.ams.PaymentOption;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayPayConsultResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayPayConsultResponse extends AlipayResponse {

  /** The payment option list. */
  private List<PaymentOption> paymentOptions;

  private List<PaymentMethodInfo> paymentMethodInfos;

  private String extendInfo;
}
