/*
 * v1_payments_reserve_inquireRelease
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.pay;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Amount;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayInquireReleaseResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInquireReleaseResponse extends AlipayResponse {

  /**
   * The request identifier originally used to create the release. Returned when result.resultStatus
   * is S.
   */
  private String releaseRequestId;

  /** The queried manual release identifier. Returned when result.resultStatus is S. */
  private String releaseId;

  /** The source manual hold identifier. Returned when result.resultStatus is S. */
  private String holdId;

  private Amount releaseAmount;

  /**
   * The release status. Possible values are SUCCESS, FAIL, and PROCESSING. SUCCESS and FAIL are
   * terminal; PROCESSING is non-terminal. Returned when result.resultStatus is S.
   */
  private String releaseStatus;
}
