/*
 * authorizations_consult
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.auth;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.AuthCodeForm;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayAuthConsultResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayAuthConsultResponse extends AlipayResponse {

  private String authUrl;

  private String extendInfo;

  /**
   * The URL that redirects users to a WAP or WEB page in the default browser or the embedded
   * WebView. Note: When the value of result.resultCode is SUCCESS, at least one of schemeUrl,
   * applinkUrl, and normalUrl is to be returned. More information: Maximum length: 2048 characters
   */
  private String normalUrl;

  /**
   * The URL scheme that redirects users to open an app in an Android or iOS system when the target
   * app is installed. Note: When the value of result.resultCode is SUCCESS, at least one of
   * schemeUrl, applinkUrl, and normalUrl is to be returned. More information: Maximum length: 2048
   * characters
   */
  private String schemeUrl;

  /**
   * The URL that redirects users to open an app when the target app is installed, or to open a WAP
   * page when the target app is not installed. For Android, the URL is a Native App Link. For iOS,
   * the URL is a Universal Link. Note: When the value of result.resultCode is SUCCESS, at least one
   * of schemeUrl, applinkUrl, and normalUrl is to be returned. More information: Maximum length:
   * 2048 characters
   */
  private String applinkUrl;

  /**
   * Android package name, which is used for Android app to open a cashier page. Note: This field is
   * returned when result.resultCode is SUCCESS and terminalType is ​APP or ​WAP​. More information:
   * Maximum length: 128 characters
   */
  private String appIdentifier;

  private AuthCodeForm authCodeForm;
}
