/*
 * aba/funds/createDirectRefund
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.aba;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Amount;
import com.alipay.global.api.model.ams.RefundFromMethod;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayCreateDirectRefundResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayCreateDirectRefundResponse extends AlipayResponse {

  /**
   * The unique ID assigned by Antom for the original payment to be refunded. Note: This field is
   * returned when the refund succeeds (the value of result.resultStatus is S). More information:
   * Maximum length: 64 characters
   */
  private String paymentId;

  /**
   * The unique ID that is assigned by Antom to identify a refund. A one-to-one correspondence
   * between refundId and refundRequestId exists. Note: This field is returned when the refund
   * succeeds (the value of result.resultStatus is S). More information: Maximum length: 64
   * characters
   */
  private String refundId;

  /**
   * The unique ID that is assigned by the merchant to identify a refund request. Note: This field
   * is returned when the refund succeeds (the value of result.resultStatus is S). More information:
   * Maximum length: 64 characters
   */
  private String refundRequestId;

  /**
   * The date and time when the refund reaches the state of success, failure, or unknown. Note: This
   * field is returned when the refund succeeds (the value of result.resultStatus is S). More
   * information: The value follows the ISO 8601 standard format. For example,
   * \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String refundTime;

  private RefundFromMethod refundFromMethod;

  private Amount refundFromAmount;

  private Amount refundToAmount;
}
