/*
 * aba-inquireCardDetail
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.aba;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.AuthorizationControl;
import com.alipay.global.api.model.ams.CardholderInfo;
import com.alipay.global.api.response.AlipayResponse;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Map;
import lombok.*;

/** AlipayInquireCardDetailResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInquireCardDetailResponse extends AlipayResponse {

  /** 卡资产ID。 Card asset Id. */
  private String assetId;

  /**
   * 由用户定义的卡昵称，可以帮助用户更方便地管理多张卡。 User-defined card nickname, designed to help users manage multiple
   * cards more conveniently.
   */
  private String cardNickName;

  /**
   * 卡状态。可取值范围： ACTIVE：可正常使用 FROZEN：已冻结 CANCEL：已注销 Card Status: Represents the current state of the
   * card. Possible values include: ACTIVE: The card is active and can be used normally. FROZEN: The
   * card has been frozen and cannot be used temporarily. CANCEL: The card has been canceled and is
   * no longer valid.
   */
  public enum CardStatusEnum {
    ACTIVE("ACTIVE"),

    FROZEN("FROZEN"),

    CANCEL("CANCEL");

    private String value;

    CardStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CardStatusEnum fromValue(String value) {
      for (CardStatusEnum b : CardStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  /**
   * 卡状态。可取值范围： ACTIVE：可正常使用 FROZEN：已冻结 CANCEL：已注销 Card Status: Represents the current state of the
   * card. Possible values include: ACTIVE: The card is active and can be used normally. FROZEN: The
   * card has been frozen and cannot be used temporarily. CANCEL: The card has been canceled and is
   * no longer valid.
   */
  private CardStatusEnum cardStatus;

  /** 脱敏卡号。 Masked card number. */
  private String maskedCardNo;

  /**
   * 卡品牌。 可取值范围： MASTERCARD Card Brand: Indicates the brand or network of the card. Possible value:
   * MASTERCARD: The card is part of the Mastercard network.
   */
  public enum CardBrandEnum {
    MASTERCARD("MASTERCARD");

    private String value;

    CardBrandEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CardBrandEnum fromValue(String value) {
      for (CardBrandEnum b : CardBrandEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  /**
   * 卡品牌。 可取值范围： MASTERCARD Card Brand: Indicates the brand or network of the card. Possible value:
   * MASTERCARD: The card is part of the Mastercard network.
   */
  private CardBrandEnum cardBrand;

  /** Datetime UTC time: 2018-10-31T00:00:00+0800. ISO 8601 */
  private String createdTime;

  /** Datetime UTC time: 2018-10-31T00:00:00+0800. ISO 8601 */
  private String updatedTime;

  /** Purpose of the card */
  private String purpose;

  /** Note information of card application */
  private String note;

  /**
   * Customer metadata in key-value format. - Key max length: 32 - Value max length: 128 - Max
   * number of keys: 30 - Total JSON string max length: 3096
   */
  private Map<String, String> metadata;

  private AuthorizationControl authorizationControl;

  private CardholderInfo cardholderinfo;
}
