/*
 * aba-inquireCardSensitiveInfo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.aba;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayInquireCardSensitiveInfoResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInquireCardSensitiveInfoResponse extends AlipayResponse {

  /**
   * 卡资产ID。 此字段只有当 result.resultStatus &#x3D; S 时才会按需返回。 Card Asset ID. This field will only be
   * returned on demand when result.resultStatus &#x3D; S.
   */
  private String assetId;

  /**
   * 加密cvv号。 此字段只有当 result.resultStatus &#x3D; S 时才会按需返回。 CVV number. This field will only be
   * returned on demand when result.resultStatus &#x3D; S.
   */
  private String cvv;

  /**
   * 加密卡号。 此字段只有当 result.resultStatus &#x3D; S 时才会按需返回。 card number. This field will only be
   * returned on demand when result.resultStatus &#x3D; S.
   */
  private String cardNo;

  /**
   * 卡片过期月份，格式为“MM“，如：”07“。 此字段只有当 result.resultStatus &#x3D; S 时才会按需返回。 Card expiration month,
   * formatted as \&quot;MM,\&quot; e.g., \&quot;07.\&quot; This field will only be returned on
   * demand when result.resultStatus &#x3D; S.
   */
  private String expiredMonth;

  /**
   * 卡片过期年份，格式为“YY“，取年份后两位数字，如：”29“。 此字段只有当 result.resultStatus &#x3D; S 时才会按需返回。 Card expiration
   * year, formatted as \&quot;YY,\&quot; using the last two digits of the year, e.g.,
   * \&quot;29.\&quot; This field will only be returned on demand when result.resultStatus &#x3D; S.
   */
  private String expiredYear;
}
