/*
 * aba/funds/inquireDirectRefund
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.aba;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Amount;
import com.alipay.global.api.model.ams.RefundFromMethod;
import com.alipay.global.api.model.ams.TransactionStatusType;
import com.alipay.global.api.response.AlipayResponse;
import lombok.*;

/** AlipayInquireDirectRefundResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInquireDirectRefundResponse extends AlipayResponse {

  private TransactionStatusType refundStatus;

  /**
   * The result message that explains the refund result code. Note: This field is returned when the
   * API is called successfully (the value of result.resultStatus is S). More information: Maximum
   * length: 256 characters
   */
  private String refundResultMessage;

  /**
   * The result code for different refund statuses. Note: This field is returned when the API is
   * called successfully (the value of result.resultStatus is S). More information: Maximum length:
   * 64 characters
   */
  private String refundResultCode;

  /**
   * The unique ID assigned by Antom to identify a refund. A one-to-one correspondence between
   * refundId and refundRequestId exists. Note: This field is returned when the API is called
   * successfully (the value of result.resultStatus is S). More information: Maximum length: 64
   * characters
   */
  private String refundId;

  /**
   * The unique ID assigned by Antom for the original payment to be refunded. Note: This field is
   * returned when the API is called successfully (the value of result.resultStatus is S). More
   * information: Maximum length: 64 characters
   */
  private String paymentId;

  /**
   * The unique ID assigned by the merchant to identify a refund request. Note: This field is
   * returned when the API is called successfully (the value of result.resultStatus is S). More
   * information: Maximum length: 64 characters
   */
  private String refundRequestId;

  /**
   * The date and time when the refund reaches a final state of success. Note: This field is
   * returned when the value of refundStatus is SUCCESS. More information: The value follows the ISO
   * 8601 standard format. For example, \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String refundTime;

  private RefundFromMethod refundFromMethod;

  private Amount refundToAmount;

  private Amount refundFromAmount;
}
