/*
 * aba-inquireCardTransactionEvent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.aba;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.CardTransactionEvent;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayInquireCardTransactionEventResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInquireCardTransactionEventResponse extends AlipayResponse {

  /**
   * The card transaction events. Returned when resultStatus is S; an empty match returns an empty
   * array.
   */
  private List<CardTransactionEvent> events;

  /** The total number of matching records. Returned when resultStatus is S. */
  private Integer totalCount;

  /** The total number of pages. Returned when resultStatus is S; an empty match returns zero. */
  private Integer totalPageNumber;

  /** The current one-based page number. Returned when resultStatus is S. */
  private Integer currentPageNumber;
}
