/*
 * aba-inquireCard
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.aba;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.Card;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayInquireCardResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayInquireCardResponse extends AlipayResponse {

  /** Total card elements. */
  private Integer totalCount;

  /** Total number of pages. */
  private Integer totalPageNumber;

  /**
   * 当前页码。 此字段只有当 result.resultStatus &#x3D; S 时才会按需返回。 Current page number This field will only be
   * returned as needed when &#x60;result.resultStatus &#x3D; S&#x60;.
   */
  private Integer currentPageNumber;

  /**
   * 卡列表 此字段只有当 result.resultStatus &#x3D; S 时才会按需返回。 Card list This field will only be returned as
   * needed when &#x60;result.resultStatus &#x3D; S&#x60;.
   */
  private List<Card> cardList;
}
